### ISSUE TITLE
Legend bug - turned on by code - Matlab

### ISSUE THREAD

**Issue by ccaprani** [matlab2tikz/matlab2tikz#1006]
Thanks for the awesome code!

**Bug Summary:**
There is no legend in a simple 2D line series plot with 4 lines. The M2T code turns it on, and so it appears in the TeX code.
Using Matlab 2017b (Prerelease) and M2T v1.1.0 on Windows.

**Cause:**
Wen querying axes object for the legend, Line 1064 of M2T has the code:
`legendhandle = legend(axisHandle);`
This actually turns the legend on with default strings ('data1', data2', etc), and so for the remaining M2T code, this default legend appears, along with 
`\addlegendentry{data1}`
in the TeX output.
This seems to be intentional design according to Matlab's documentation on Legend command.

**Suggested solution:**
Replace:
`legendhandle = legend(axisHandle);`
with
`legendhandle =findobj(axisHandle,'tag','legend');`
which does not turn on legend when querying its existence. Tested under my environment.

**Comment by ccaprani** [comment]
Urm...my proposed fix has issues :-( 

From 2014b, Matlab switched to the new HG2 graphics. In this system, legends are not children of axes and so the search for the tag returns 0x0 handle. Instead, legends are siblings of axes, and children of the figure handle. Here are some refs about his:
[https://au.mathworks.com/help/matlab/graphics_transition/why-are-colorbars-and-legends-not-valid-axes-handles.html](url)
[https://au.mathworks.com/help/matlab/creating_plots/graphics-objects.html#bt_vzt7](url)
[http://undocumentedmatlab.com/blog/plot-legend-title](url)

Since in the function, we only have the axisHandle, we wish to search the parent object of the axisHandle to see if it has the legend (i.e. the figure of the axes, which is most likely 'gcf'. but let's not assume so). Hence, we can use:
`legendhandle=findobj(axisHandle.Parent,'tag','legend');`
instead of the line I had previously.

The issue with this approach is the assumption that this legend is for this axes. In the (common) cases of multiple legends for multiple axes in a single figure, some sort of searching and matching must be done between the axes and legends, using 
`legendhandle.PlotChildren(1).Parent`
to find the axes of the current legend.

**Comment by mattia-** [comment]
Hi! I found the same bug while using matlab2tikz v 1.1.0 with MATLAB r2017b. 

Has this been solved already, maybe in a pull request or something? 

I tried to fix it (and I did, at least as far as the plots I needed are concerned), so I wanted to share it, but I am now wondering if there are any cases I haven't considered and that may break my fix. For example, I am not entirely sure what you mean by "multiple legends for multiple axes in a single figure", could you maybe provide a MWE for that? I tried with subplots, each with its own legend:
```
clear
clc
close all

x = 0:0.1:1;

figure()
subplot(1,2,1)
plot (x, sin(x));
legend('sin');

subplot(1,2,2)
plot (x, cos(x));
legend('cos');
```
and the output tikz file gives just the right plot with my fix, but maybe I misunderstood.


My (extremely naive) attempt to a fix was to replace the line
`legendhandle = legend(axisHandle);`
(which you mentioned above) with the following snippet:
```
% check whether legend is a property of the axis object or not
if isprop(axisHandle, 'legend') % new behaviour for r2017b
    legendhandle = axisHandle.Legend;
else % fall back to old behaviour
    legendhandle = legend(axisHandle);
end
```

I hadn't even though of getting the figure handle using `axisHandle.Parent`, to be honest.

Would this reliably work? Are there any cases you can think of that would break this fix?

**Comment by RlndVt** [comment]
@mattia- Please create a pull request for your fix.

**Comment by saveriob** [comment]
Has this bug returned?
I am using Matlab 2018a and I have the same problem (all plots have a legend that I didn't ask for).
The M2T function seems to have the old `legendhandle = legend(axisHandle);` line that was causing the problem in the first place.

**Comment by egeerardyn** [comment]
This has not been integrated yet.

**Comment by jbjorsell** [comment]
I haven't looked too deep into this but I tried to exchange Line 1064 of M2T from 
`legendhandle = legend(axisHandle);` to `legend handle = axisHandle.Legend` as this should get the associated legend if it exist. In my limited examples it seems to work.

**Comment by MarkusWnuk** [comment]
Thank you jbjorsell, fixed my bug as well. 
Simply changed 
legendhandle = legend(axisHandle);  in line 1064
to 
legendhandle = axisHandle.Legend;

**Comment by egeerardyn** [comment]
This is fixed in #1046, which is integrated into the latest develop branch.

**Comment by prittjam** [comment]
The legend bug seems to have returned in 2018a. I pulled from the development branch, but legends are showing again despite being turned off.

**Comment by tmattner** [comment]
Observed same issue for MATLAB 2020a. Fixed by changing line 1074 to legendhandle = axisHandle.Legend; as per suggestion above.
