### ISSUE TITLE
Horizontal error bars

### ISSUE THREAD

**Issue by JseMJ** [matlab2tikz/matlab2tikz#1016]
I have a plot in matlab with horizontal error bars, but when I use matlab2tikz they get left behind (images below) - is there a solution to this?
![matlabfigure](https://user-images.githubusercontent.com/32747530/31512232-32568dc6-af58-11e7-8144-905e16065d21.jpg)
![screenshot 2017-10-12 10 19 20](https://user-images.githubusercontent.com/32747530/31512241-3a6da68e-af58-11e7-878d-6d2e8f3cb6ad.png)

**Comment by egeerardyn** [comment]
Thanks for reporting this. Could you elaborate how you made this plot (i.e. which version of MATLAB/what code you used/...)?
If I remember correctly, m2t can convert horizontal error bars, e.g. as produced with the `herrorbar` function (there is a copy inside `test/suites/private` of this repository, but the original version is also on FileExchange).

**Comment by JseMJ** [comment]
Thanks, I will try herrorbar. I was working in Matlab 2017b, and here is my code:
```
y = [604.40,599.84,602.23,616.96,582.62,575.40,570.14,572.77,574.53];
x =  [4.05  ,4.05  ,4.05  ,4.05  ,4.20  ,4.37  ,4.55  ,4.55  ,4.37  ];
ebars =  [0.0563,0.0563,0.0326,0.0326,0.0350,0.0254,0.0437,0.0437,0.0254];
figure(1)
clf
errorbar(x,y,2*ebars,'horizontal','o')
legend('s1');
```

**Comment by raimund-schluessler** [comment]
You can test https://github.com/matlab2tikz/matlab2tikz/pull/1019 now.
