### ISSUE TITLE
matlab2tikz adds legend to plot before generating tikz

### ISSUE THREAD

**Issue by sambura** [matlab2tikz/matlab2tikz#1018]
With Matlab R2017b and matlab2tikz 1.1 a legend is added to a figure when invoking matlab2tikz. Unnamed lines are labeled width, e.g., "data1". I used not to have this problem in the past. 

Reproduce with matlab code:

`plot(1:100)`
`matlab2tikz('mwe.tex', 'standalone', true);`

**Comment by egeerardyn** [comment]
This is a duplicate of #1006
