### ISSUE TITLE
Part of the plot is missing

### ISSUE THREAD

**Issue by th33r453r** [matlab2tikz/matlab2tikz#1022]
Hi guys,

i´m sorry bothering you, but i just cannot figure out, what I am doing wrong.
I exported a figure from MATLAB R2014a. It contains two plots.

I used the following MATLAB Code:
```
figure,
plot(t,signalA,'b--'),
hold on,grid on,
plot(t,signalB,'black')
legend('Drumspeed_{current}','Drumspeed_{wanted}')
```

(All vectors contain 5601 Elements)

I exported it, using
`matlab2tikz( 'Drumspeed_compare.tex', 'width', '0.8\fwidth')`

I use matlab2tikz version v1.1.0.

Problem:
---------
If I put it into LaTex I just see the last parts of both plots - like 1/3 of the plot. The first part of both plots is missing.
I tried to remove "forget plot" but then the colorstyle and linestyle of my legend looks all the same (solid and black).
I think it has something to do with the "\addlegendentry" or "forget plot" but i don´t have a clue what i am missing. I tried it for the last 3h. :/

Can you help me please`?

Best regards.

Chris

Here is the original exported file from MATLAB (I deleted some lines...)

```
\begin{tikzpicture}

\begin{axis}[%
width=0.763\fwidth,
height=0.6\fwidth,
at={(0\fwidth,0\fwidth)},
scale only axis,
separate axis lines,
every outer x axis line/.append style={black},
every x tick label/.append style={font=\color{black}},
every x tick/.append style={black},
xmin=0,
xmax=18,
xlabel={Zeit \ s},
every outer y axis line/.append style={black},
every y tick label/.append style={font=\color{black}},
every y tick/.append style={black},
ymin=-55,
ymax=55,
ylabel={Trommeldrehzahl \ rpm},
axis background/.style={fill=white},
xmajorgrids,
ymajorgrids,
legend style={legend cell align=left, align=left, draw=black}
]
\addplot [color=blue, dashed, forget plot]
  table[row sep=crcr]{%
0	-0.086618\\
0.00321428571428571	-0.022524\\
0.00642857142857143	0.045379\\
0.00964285714285714	-0.129513\\
... some more lines with numbers....
17.9935714285714	0.062521\\
17.9967857142857	0.049354\\
18	0.006045\\
};
\addlegendentry{$\text{Drumspeed}_{\text{current}}$}

\addplot [color=black, forget plot]
  table[row sep=crcr]{%
0	0\\
0.00321428571428571	0\\
0.00642857142857143	0\\
... some more lines with numbers....
17.9935714285714	0\\
17.9967857142857	0\\
18	0\\
};
\addlegendentry{$\text{Drumspeed}_{\text{wanted}}$}

\end{axis}
\end{tikzpicture}%
```

**Comment by th33r453r** [comment]
I solved it.

I was using pgfplots 1.12... 
If someone else has the same problem:
I updated it, using tlgmgr.
`tlmgr update pgfplots`

Sorry guys...

**Comment by egeerardyn** [comment]
Thanks for letting us know you solved it!
