### ISSUE TITLE
Export only zoomed part

### ISSUE THREAD

**Issue by CsatiZoltan** [matlab2tikz/matlab2tikz#1027]
Irrespective of zooming, *matlab2tikz* exports the whole figure, not only the zoomed part. Is it possible to export the zoomed region?

**Comment by egeerardyn** [comment]
Do you have an example?

Matlab2tikz should export only the visible part of the figure; however, it will export all the data. So if you have zoomed into a very small part, the LaTeX/pgfplots computational engine may not be able to deal with the dynamic range.
If you want to remove the invisible data (of the most common types of plots, i.e. lines and so on), the `cleanfigure` function may help you out.

**Comment by CsatiZoltan** [comment]
When I saw the large file size despite the zoomed region, I didn't compile it to see if only the zoomed part is plotted. Now I see it works as intended.
