### ISSUE TITLE
export styles for Axis as external

### ISSUE THREAD

**Issue by maldag** [matlab2tikz/matlab2tikz#1037]
Writing a bigger document I prefer to have all axes plots in the same style regarding title labels, axis labels, font sizes.
PGFPlots and tikz support the option, to create an own styleset for this and refer to it in each axis environment. Matlab2tikz could split the desired styles into global and local ones.

**Comment by egeerardyn** [comment]
I fully agree with you: in big documents, managing the styles becomes a challenge.
I think this is strongly related to (or even the same as) #262, what do you think?

**Comment by maldag** [comment]
Yes, this seems familiar to me.

**Comment by egeerardyn** [comment]
Okay, then I'll close this as duplicate; if you have something interesting to add, please feel free to do so in #262 then 👍
