### ISSUE TITLE
Jagged lines produced for smooth plot

### ISSUE THREAD

**Issue by CsatiZoltan** [matlab2tikz/matlab2tikz#1040]
I have the following plot.
![frommatlab](https://user-images.githubusercontent.com/12742890/42992981-8169ec0c-8c0a-11e8-9b6e-d88ad3341764.PNG)
Note that the green line is almost smooth and the black line also has little oscillations. However, when exported to tikz, it results the following pdf
[3ptLoadDisplacement3.pdf](https://github.com/matlab2tikz/matlab2tikz/files/2213210/3ptLoadDisplacement3.pdf)
To be able to reproduce the issue, I attached both the [Matlab figure](https://ufile.io/gnbn5) and the generated tex file (with modification in the preamble):
[3ptLoadDisplacement3.tex.txt](https://github.com/matlab2tikz/matlab2tikz/files/2213244/3ptLoadDisplacement3.tex.txt)
I tried the 1.1.0 stable release and the newest develop version. Both produced the same file.

**Comment by egeerardyn** [comment]
Have you tried running `cleanfigure` on this plot? I would guess that will reduce the complexity of the data you are plotting and in the process also reduce compilation time.

**Comment by CsatiZoltan** [comment]
Now I tried `cleanfigure`. It resulted smaller text file size and also smaller pdf file size, but the jaggedness remained.

**Comment by okomarov** [comment]
@CsatiZoltan You need to change the `line join` option to see whichever works best for you: https://tex.stackexchange.com/questions/15690/how-can-i-prevent-pgfplots-from-rendering-lines-incorrectly-when-i-use-no-marke

**Comment by CsatiZoltan** [comment]
Works like a charm! Thanks a lot. Your link might be useful to be put into the [wiki](https://github.com/matlab2tikz/matlab2tikz/wiki).
