### ISSUE TITLE
transparent background color

### ISSUE THREAD

**Issue by YangangCao** [matlab2tikz/matlab2tikz#1052]
Actually, the background color of graph is the same as the pdf document, however, it will cover the watermark if exists, transparent background color achieved by doing this:

change the code in matlab2tikz.m  row 1363:

m2t = m2t_addAxisOption(m2t, 'axis background/.style', sprintf('{fill=%s}', col));

to:

m2t = m2t_addAxisOption(m2t, '%axis background/.style', sprintf('{fill=%s}', col));

**Comment by egeerardyn** [comment]
Hi,
while your patch may solve your particular problem, in matlab2tikz we try to recreate the intent of your MATLAB figure in TikZ/pgfplots, which I don't think your patch accomplishes.
In this case, I think we are doing the right thing for most people.

There are other ways around this for your use-case:
1. in MATLAB, you can do something like `set(gca, 'Color', 'none')` to remove the background color
2. in your TikZ code, you can also tweak the output to ensure that property is set to "none".
