### ISSUE TITLE
Legend gets created for plots that don't have one

### ISSUE THREAD

**Issue by rajb245** [matlab2tikz/matlab2tikz#1056]
On my MATLAB (Windows "9.4.0.813654 (R2018a)"), the following line in matlab2tikz creates a legend with a label "data1" for a plot that otherwise has no label:
https://github.com/matlab2tikz/matlab2tikz/blob/62a038d9833d4d48581acb630da550e40799338f/src/matlab2tikz.m#L1071

The issue is that the plot looks one way before i call matlab2tikz, and then after, a legend got added and the unwanted legend ends up in the tex file.

If we're trying to get the handle to the legend, then I suggest replacing the problematic line with
`legendhandle = axisHandle.Legend;`

I'm not sure how portable that is though to octave or older matlab when the plotting system API wasn't as clearly object oriented. Maybe there is some equivalent `get(axisHandle,'Legend')` or something for older MATLAB.

Minimum example to exercise the bug:
`figure, plot(0:1);
matlab2tikz('bugReport.tex'); `

**Comment by leptoceratops** [comment]
I would like to report the same problem for MATLAB R2019b. The solution suggested by @rajb245 works.

**Comment by rajb245** [comment]
I took the idea that worked for me and @leptoceratops and made a PR out of it (see above).

**Comment by OgreTransporter** [comment]
Works for me, too. It would be nice to accept and merge the PR.

**Comment by ThexXTURBOXx** [comment]
I think, this can be closed since it has been resolved in https://github.com/matlab2tikz/matlab2tikz/commit/111b1ba878f7f5e53a45fff171bb3af79977e9a5
