### ISSUE TITLE
My axis values are gone when using matlab2tikz

### ISSUE THREAD

**Issue by dennissde** [matlab2tikz/matlab2tikz#1078]
Hi, I hope you can help me.

I made a figure in Matlab with several xtick labels and yticklabels on the axes.
But when I use matlab2tikz the axes are empty (moreoever the x-axis is pointing to the left and not to the right)..

What am I doing wrong? - Without the xtick labels and ytick labels my plot is meaningless.

**Comment by egeerardyn** [comment]
Without any code this cannot be reproduced.
