### ISSUE TITLE
Is there a way to convert a png-figure directly into a TikZ-figure using matlab2tikz without generating an auxiliary png-file?

### ISSUE THREAD

**Issue by dennissde** [matlab2tikz/matlab2tikz#1079]
I have the following problem:
I have a file file.png which I want to convert to use it for TikZ.

Calling

FILE = imread('file.png');
imshow('FILE');

I get a matlab figure, of course.

But when I now do

cleanfigure;
matlab2tikz('file.tex')

this produces an extra png-file which has to be included into the TikZ-code.
I think thats not really what I want.

Is there a direct way to get a TikZ-picture without an extra png-file?

**Comment by egeerardyn** [comment]
There is an option not to generate PNG files, it's documented in the [help](https://github.com/matlab2tikz/matlab2tikz/blob/develop/src/matlab2tikz.m#L31). Please check that for all the other options that are available 🙂

Anyhow, generating the PNG files is what most people want in the generic case. That's the reason why matlab2tikz does what it does: creating the image as PNG is lossless, space-efficient (by a huge amount), and time-efficient for compilation (also by a huge amount). The alternative is provided for the rare edge cases (e.g. tiny figures, you need a single file for some weird publisher, ...), but in general discouraged.
