### ISSUE TITLE
Matlab2tikz for Figure with  stackedplot doesn't work ???

### ISSUE THREAD

**Issue by domthi** [matlab2tikz/matlab2tikz#1081]
If I create a figure with stackedplot() and want to convert it to tikz with malab2tikz, the following warning appears and the  tikz- file does not contain the plotted points.   Why doesn't Matlab2tikz work with stackedplot?
 *** 
Warning: Don't know annotation 'matlab.graphics.shape.internal.Button'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337) 
Warning: Don't know annotation 'matlab.graphics.shape.internal.Button'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337) 
Warning: Don't know annotation 'matlab.ui.controls.ToolbarPushButton'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337) 
Warning: Don't know annotation 'matlab.ui.controls.ToolbarPushButton'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337) 
Warning: Don't know annotation 'matlab.ui.controls.AxesToolbar'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337) 
Warning: Don't know annotation 'matlab.ui.controls.AxesToolbar'. 
> In matlab2tikz>userWarning (line 5937)
  In matlab2tikz>drawAnnotationsHelper (line 3061)
  In matlab2tikz>drawAnnotations (line 3006)
  In matlab2tikz>saveToFile (line 494)
  In matlab2tikz (line 337)

**Comment by Pratched** [comment]
Is there a reason as to why this was closed instantly? I am experiencing the same problem? Is 'stackedplot' not supported?
