### ISSUE TITLE
Can't understand this solution!! Can anyone explain?

### ISSUE THREAD

**Issue by adnanbinamer** [matlab2tikz/matlab2tikz#1088]
![Screenshot_20200925-182109.jpg](https://user-images.githubusercontent.com/71884229/94269190-ef4b0780-ff5b-11ea-8163-a3c29bc1e7c9.jpg)

**Comment by adnanbinamer** [comment]
Hey

**Comment by egeerardyn** [comment]
This has nothing to do with matlab2tikz.
