### ISSUE TITLE
Prevent matlab2tikz to generate separate tsv-files when using 'externalData' option

### ISSUE THREAD

**Issue by steradiant** [matlab2tikz/matlab2tikz#1095]
Hello,
I'm using the 'externalData' option in matlab2tikz. At a certain amount of data, matlab2tikz automatically splits the data from one single plot into different tsv-files. I'd like to have an option where I can prevent this behaviour. I want all data in one tsv file, no matter how big it gets.

**Comment by egeerardyn** [comment]
There is already an option for that: `maxChunkLength`. 

Though, you should not be surprised if your TikZ file no longer compiles after that: in most LaTeX compilers (pdflatex/latex worse so than lualatex, iirc) that chunk length is exactly there to give the compiler a bit of breathing room between different plots.
