### ISSUE TITLE
matlab2tikz generates empty tikz-file when creating polarplot

### ISSUE THREAD

**Issue by vanKey2022** [matlab2tikz/matlab2tikz#1116]
Hello all,

since several month I'm working with matlab2tikz and made good experiences. Right now, im trying to do a polarplot and convert it into a tikz-File to include it in Latex. The problem is, that matlab2tikz generates an empty tikz-File when creating a polarplot (see minimum example code). Does anyone have an idea how to solve the problem?

Kind regards
vanKey2022

Minimum example code, that does not work:
`
clear all

close all

theta = 0:0.01:2*pi;

rho = sin(2*theta).cos(2theta);

polarplot(theta,rho)

matlab2tikz('C:\Users\Name\Desktop\Polarplot.tikz', 'height', '5cm', 'width', '5cm');
`

**Comment by egeerardyn** [comment]
See #1115
