### ISSUE TITLE
Disproportionate axis with pzmap() and rlocus()

### ISSUE THREAD

**Issue by perfran** [matlab2tikz/matlab2tikz#177]
Hello, 

I would like to report an issue with the functions pzmap and rlocus that display the complex plane with poles and zeros of a transfer function.
The problem is that the are incorrectly scaled, much larger than needed (up to 2*10^98) . As a consequence, the poles and zeroes appear to be only one point in the center of the plot.

Here is a short example code:

```
s=tf('s');
rlocus(tf([1 1],[4 3 1]))
matlab2tikz('locustest.tikz')
```

**Comment by egeerardyn** [comment]
This seems to work OK with the 1.0.0 release when `cleanfigure` is used. Maybe the new Opheim simplification algorithm as hinted in #666 changes this, but that's a different story.
