### ISSUE TITLE
bug with legends on figures with patch (or fill) in octave 3.6.4 (works in matlab)

### ISSUE THREAD

**Issue by houtanb** [matlab2tikz/matlab2tikz#200]
Example to reproduce the error included below. It plots a line, plots a patch, moves the patch to the bottom, creates a legend, calls matlab2tikz and saves the plot as a .jpg so you can see the difference between the tikz version and the version actually produced by octave. The line in the legend shows up as a thin black line whereas the line plotted is a dashed, thick green line.

```matlab
x = 0:10;
y = x;

h = figure;
hold on;

line_handles(1) = line('XData', x, 'YData', y, 'Color', 'green', 'LineStyle', '--', 'LineWidth', 3);

yrange = get(gca, 'YLim');

sh = patch([repmat(7, 1, 2) repmat(10, 1, 2)], ...
	   [yrange fliplr(yrange)], 'yellow');
children = get(gca, 'children');
children = [children(2:end); sh];
set(gca, 'children', children);

legend(line_handles, {'l1', 'l2'}, ...
       'orientation', 'horizontal', ...
       'location', 'southeast');

disp('m2tikz');
matlab2tikz('filename', 'm2tz.tex', ...
            'showInfo', false, ...
            'showWarnings', false, ...
            'checkForUpdates', false);

disp('saveas');
saveas(h, 'm2tz.jpg','jpg');
```

**Comment by okomarov** [comment]
The OP's code is not fully valid and re-created a minimal example of what the OP might have wanted to achieve:
```matlab
x    = 0:10;
h(1) = line(x,x, 'Color', 'green', 'LineStyle', '--', 'LineWidth', 3);
hold on
yLim = get(gca, 'YLim');
h(2) = patch([7, 7, 10, 10], [yLim fliplr(yLim)],'yellow');
legend(h, {'l1', 'l2'}, 'location', 'southeast');
```
The result:

![capture](https://cloud.githubusercontent.com/assets/3731173/5808320/05a07e2c-a024-11e4-829a-e793816e5430.PNG)

The Octave figure does not seem to respect the plotting order but otherwise the `m2t` output is correct. Therefore closing this issue.
