### ISSUE TITLE
Issue with number of points

### ISSUE THREAD

**Issue by ghost** [matlab2tikz/matlab2tikz#249]
Dear all

When running this code

t=1:19838;
x=randn(t,1);

plot(t,x)
cleanfigure;
matlab2tikz('myfile.tex');

I get the following error when I compile my tex file with pdflatex

```
   ! TeX capacity exceeded, sorry [main memory size=5000000].
```

Is there an easy workaround for this (when there are too many data points)?

Cheers!

**Comment by LukasDrude** [comment]
The link changed to:
https://github.com/matlab2tikz/matlab2tikz/wiki/TeX-capacity-exceeded,-sorry

**Comment by PeterPablo** [comment]
Specifying a more restricting `'floatFormat'` like `%.3f` also helps a lot and is an easy solution. Modification of the format though should be done with care since there are cases, where this yields reduced *graphical resolution*.

**Comment by egeerardyn** [comment]
@PeterPablo good idea: feel free to adapt the wiki as such :smile:
