### ISSUE TITLE
matlab2tikz and dirplot/polar (polar plot)

### ISSUE THREAD

**Issue by flobsi** [matlab2tikz/matlab2tikz#257]
I've got a question concerning matlab2tikz:
I'm using [`dirplot`](http://www.mathworks.com/matlabcentral/fileexchange/1251-dirplot) (similar to 'polar') to create a polar plot. However, when I generate a tikz-file and run it with latex, only the lines are plotted - no labeling or legend or title. Small example:
```matlab
angle_deg = [-90, -60, -30, 0, 30, 60, 90]; 
gain = [70, 80, 85, 90,  85, 80, 70];
dirplot(angle_deg, gain, 'r');
% or instead of the previous line: polar(angle_deg, gain, 'r');
matlab2tikz('test_dirplot_tikz.tikz', 'height', '\figureheight', 'width', '\figurewidth','showInfo', false);
```
Any suggestions?
Thanks

**Comment by okomarov** [comment]
This is a FEX submission which sets the label's `handlevisibility` to `off`. I reckon there is no way for us to detect such plot (thus removing from the milestone). Workaround by egeerardyn applies or edit handle visibility in `dirplot()` directly.

**Comment by egeerardyn** [comment]
@okomarov You are right. I assumed this was a built-in thing (I've linked it into the issue report above).
I have had a little look at the source code, and while it does seem to produce quite nice-looking figures, I don't see a way for us to determine whether `dirplot` has been used to generate a certain plot.
The only thing that is somewhat special, is the use of `UserData` where a three-vector is stored. But that format is way to general to trigger special handling of such figures.

If you do want an automatic fix for this: for us it would be sufficient to have the relevant axis "tagged" e.g. with `dirplot` (e.g. `set(gca,'Tag','dirplot')`). But this is best left to the `dirplot` function of course. In that case we might even be able to convert this to a pgfplots polar plot?

As the work-around exists and I see no reasonable thing we can do on our end to fix this, I will be closing this. Feel free to re-open if the situation has changed.

**Comment by vanKey2022** [comment]
Hello,

right now, I'm using the polarplot function in matlab and do not get anything out with matlab2tikz (only produces empty file). Can anyone help me out here?
Kind regards
