### ISSUE TITLE
XAxisLocation on top, does not print bottom axis

### ISSUE THREAD

**Issue by farouqM** [matlab2tikz/matlab2tikz#259]
Hello,
I already asked the same question on the mathworks, and you requested me to ask it hier, as it sounds a s a bug matlab2tikz, although I still find it an excellent job that you did. Here is a simple matlab code

```
t=0:0.01:3;
x1=sin(2*t);
x2=cos(3*t);

figure;plot(t,x1,'b',t,x2,'r');set(gca,'XAxisLocation','top'); 
xlabel('t');ylabel('x')
text(1.28,0.5494,'w=2')
text(2.44,0.509,'w=3','BackgroundColor',[1 1 .6])

matlab2tikz('Test.tikz')
```

Unfortunatelly, I couldn't upload any images because I gopt an unknown error.

Thanks in advance.

**Comment by PeterPablo** [comment]
Works properly thanks to the fix from @okomarov.
![image](https://cloud.githubusercontent.com/assets/4340267/5700188/e0669a56-9a38-11e4-9ce7-98912bf8620c.png)
