### ISSUE TITLE
Surfplot Issue

### ISSUE THREAD

**Issue by illywo** [matlab2tikz/matlab2tikz#267]
I've just run into an issue with surfplots which seems to be related to the view specification of a surf plot. I've attached 4 Images. 2 are exported directly from Matlab as pdf an look how the tikz plots are intended to look like when plotted in the tex file. The 2 others are the actual tikz plots. One can see that in the one tikz plot »higher values« are somehow not displayed correctly if »lower values« are plotted afterwards. So it somehow depends on the plotting order to reproduce this bug. Can anyone explain this behavior?

Cheers,
illywo
![matlab_plot_1](https://f.cloud.github.com/assets/5088996/1648795/1824cbd8-59c2-11e3-9486-7c7103a37f8c.jpeg)
![matlab_plot_2](https://f.cloud.github.com/assets/5088996/1648796/18277586-59c2-11e3-9342-3a258e819b17.jpeg)
![tikz_plot_1](https://f.cloud.github.com/assets/5088996/1648797/18296a30-59c2-11e3-905b-69c5d9c359da.jpeg)
![tikz_plot_2](https://f.cloud.github.com/assets/5088996/1648798/182c1168-59c2-11e3-84b2-77d6f353f0cf.jpeg)

**Comment by okomarov** [comment]
With https://github.com/matlab2tikz/matlab2tikz/commit/027dfd22ac2760cafa215bac794b1e623646bcd9 surf plots with flat shader use `z buffer = sort`. This should have been resolved. (To re-open please supply test case)
