### ISSUE TITLE
Reducing the number of datapoints in a plot. 

### ISSUE THREAD

**Issue by WG-** [matlab2tikz/matlab2tikz#281]
It is known that the compile time of tikz suffers a lot when there are a lot of datapoints. Now I have this matlab figure, 6 subplots, which you can download here: https://dl.dropboxusercontent.com/u/20782274/block_xs_1e-3.fig

Now if I just export this the file is 37 Megabytes which is really to much to compile with lualatex, it really takes a long time. 

Now I tried cleanfigure(), cleanfigure('minimumPointsDistance',0.001) and cleanfigure('handle',h,'minimumPointsDistance',0.001). Herein h is the handle of one of the subplots e.g. h = subplot(2,3,1).

However none of these methods actually work and reduce the number of datapoints :( 

What I want to establish with this issue that well I want my current issue resolved and to point this out that the minimumPointsDistance does not actually work as expected.

**Comment by widdma** [comment]
Hi all, I too have had a go at adding line simplification to the cleanfigure function. My approach uses the Visvalingam--Whyatt algorithm, which iteratively removes points based the area of the triangle it creates with its neighbours. It's therefore fine for non-monotonic data. 

It also selects a tolerance based a target output size and resolution, which defaults to 15cm x 9cm @ 600ppcm. 

Runtime is O(n log(n)) in the number of points.

It resides in the line-simp branch of [widdma/matlab2tikz](https://github.com/widdma/matlab2tikz).
Tests, comments and suggestions are welcome.

**Comment by egeerardyn** [comment]
@widdma Looks fine. If you file a pull request, it's easier for everybody to inspect your changes and comment on them.

**Comment by PeterPablo** [comment]
I was about to write the same. Please file the PR against `develop` branch. It looks like you applied your changes to that anyhow :smile:

**Comment by nschloe** [comment]
@widdma Nice idea! This is so much more appropriate than the crude `minimumPointsDistance` we've had.
@PeterPablo Thanks for sharing the links.

**Comment by egeerardyn** [comment]
This should be fixed by means of #571.
