### ISSUE TITLE
Text placement: Z-ordering

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#313]
Text labels should be placed above graphs (or should ideally respect the Z-ordering of he MATLAB figure).

In TikZ, this is done using layers, so text could be placed on a layer above graphical `pgfplots` objects.

**Comment by okomarov** [comment]
This has been taken care in #534 (Annotations HG2) since the layer with the annotations is drawn last, after all other axes (both in HG1 and HG2)
