### ISSUE TITLE
Scaled arrow heads in quiver plot

### ISSUE THREAD

**Issue by SteffenT** [matlab2tikz/matlab2tikz#334]
When exporting a quiver plot with matlab2tikz, the result is very different from the figure in Matlab due to the constant arrow head size. Is there a way to use the same variable head sizes as in Matlab?

Thanks 
Steffen

**Comment by egeerardyn** [comment]
This is mostly implemented in #690 (although there is some work to be done in #691), so I think we can close this one here.
