### ISSUE TITLE
Multiple `bar` plots give incorrect bar width

### ISSUE THREAD

**Issue by AmuH** [matlab2tikz/matlab2tikz#338]
The bar-plot with facecolor doens't work with matlab2tikz.
```
A = [1,2,3];
hold on
bar([1], A(1),'FaceColor','r');
bar([2:3], A(2:3),'FaceColor','b');
```
This is the Matlab-ouput:
![matlab](https://cloud.githubusercontent.com/assets/7497528/2929256/38695bfa-d787-11e3-9a76-63bb4e60ad5a.png)
And this is the result of matlab2tikz used in LaTex:
![latex](https://cloud.githubusercontent.com/assets/7497528/2929258/3dbb870e-d787-11e3-831f-91c6cfb33291.png)

Is there a workaround?

**Comment by PeterPablo** [comment]
Fixed by PR #503.
Output of R2014b with current head of branch `develop`:
![image](https://cloud.githubusercontent.com/assets/4340267/5702831/82f5c740-9a5e-11e4-8a35-f17c08b9d3c7.png)
