### ISSUE TITLE
Pgfplot matlab2tikz problem with added text. 

### ISSUE THREAD

**Issue by sharahamo** [matlab2tikz/matlab2tikz#349]
I have the same issue with #175 where in the code, there's `addplot3` in the tikz file,

```
\addplot3[%
mesh,
shader=flat,
colormap/jet,
point meta=explicit,
mesh/rows=2]
table[row sep=crcr,header=false,meta index=3] {%
%
0.3625	0.670428571428572	0	nan\\
};
```

which in that link says it's the `nan` that causes problem. 
but it's not said there how to save it. Can anyone tell me?

**Comment by okomarov** [comment]
NaN handling in cdata problem is reported in https://github.com/matlab2tikz/matlab2tikz/issues/331. R2014a supports annotation while feature request for annotation support in HG2 is logged on https://github.com/matlab2tikz/matlab2tikz/issues/384. Closing because duplicate.
