### ISSUE TITLE
automatic testing

### ISSUE THREAD

**Issue by nschloe** [matlab2tikz/matlab2tikz#351]
We should get a little more serious about our unit/capability tests. Right now, you have to compile all figures and manually look at them to see if something is up. A better way may be to store reference outputs and compare them automatically to what mpl2tikz produces. [Image diffing](http://stackoverflow.com/questions/5132749/imagemagick-diff-an-image) may come in handy.

**Comment by PeterPablo** [comment]
Pull request #485 is related and discussion in issue #470 and #475. Should we close here?

**Comment by PeterPablo** [comment]
We also might think a little bit out of the box -- do you see a change in asking *The MathWorks* for a license specific to automated testing? (Certainly questions about "how we would prevent fraud" arise -- but first things first..)

**Comment by egeerardyn** [comment]
@PeterPablo There is no harm in asking TMW for a license for that purpose. But I think the chances are very slim and I suspect it would take a long time to actually get hold of the license (if they would appoint one).
Also, in that case we need to think about which architecture we need to run this on.

Some other projects use the MATLAB compiler, upload the compiled code to Travis and load the freely available MATLAB runtime to test their code on Travis. But that is not so straightforward, either.

**Comment by egeerardyn** [comment]
Closing this, #574 should be enough to remind us to contact them.
