### ISSUE TITLE
R2014b: text boxes aren't always handled

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#378]
As reported in #344, the abs text in test case `80` is missing when running in MATLAB R2014b.

![screen shot 2014-10-27 at 08 47 53](https://cloud.githubusercontent.com/assets/177360/4787605/b67880aa-5dad-11e4-82a4-4833d8619df1.png)

**Comment by okomarov** [comment]
The problem is actually in `cleanfigure` which switches the text visibility to `off`. It carries a test on the extent property to check for overlap (with the axes?), which does not pass because the extent is all NaNs.

**Comment by PeterPablo** [comment]
Thank you for checking! So we need to come up with a way to reliably determine the extent of 3d axis objects it seems.

**Comment by okomarov** [comment]
From what I understand we do not want to be plotting the title, xyz labels and the tickmarks as separate command in pgplots. The extent is a proxy to filter those text objects out. 

We could check if the handle is not a title or xyz label. However, we would need to discriminate boxplot labels (?). Also, I do not think those are currently handled properly anyways.

**Comment by PeterPablo** [comment]
You are right that we only want to add separate TikZ commands if the appearance is caused by (manual) user interaction. Otherwise the defaults of pgfplots/TikZ should be applied.

I agree that the whole labeling mechanism needs to be overhauled. As you know there are some open issues linked to labels one way or another (colobar tick labels, HG2, textboxes, ...).

**Comment by PeterPablo** [comment]
@okomarov, due to the precise pointer of you I was able to prepare a fix. Thank you!

**Comment by PeterPablo** [comment]
This issue is fixed, though at some point we might reconsider the removal of textboxes outside an axis, which is currently done on (manual) execution of `cleanfigure()`.
