### ISSUE TITLE
R2014b: convert filled contour plots

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#379]
As in #344: Filled contour plots are replaced by unfilled ones (as `pgfplots` only supports the latter and R2014b supplies insufficient data to manually build a contour plot without more intricate work).

Ideas how these would be implemented best are welcome.

**Comment by okomarov** [comment]
Solved with https://github.com/matlab2tikz/matlab2tikz/issues/500.
