### ISSUE TITLE
Reduce complexity of the code

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#391]
I've recently run `mlint -cyc` (or `checkcode -cyc`) on the current (i.e. 4202e7360d7e42aa24b7668e26c3dad3a7dfc1d5)  `matlab2tikz.m` file to determine the [cyclomatic complexity](http://en.wikipedia.org/wiki/Cyclomatic_complexity). This is a rough estimate of how complicated a function is and it basically measures how many paths there are through a function (e.g. `if`s, `switch/case`es, `return`s typically increase this measure) there are in the function, which again is a rough estimate of how hard the code is to understand, test and maintain.

Ideally, each function should have a complexity of less than about `10`, unless there are good reasons why it should be more complex. Below is a table that shows the cyclomatic complexity of every function we have:

Line | Function                     | Complexity
----:|:-----------------------------|:---------:
723  | `drawAxes`                   | 51         
3740 | `getLegendOpts`              | 37         
2233 | `drawText`                   | 28         
576  | `handleAllChildren`          | 27    
        | *others removed for brevity* |    

As with any metric, the results have to be interpreted with due care and not every value `>10` is by definition bad, but it might be an indication too much is being done in a single function. 
The following list of functions should be re-evaluated to see whether we can make them simpler (e.g. by introducing new functions) or whether the complexity is inherent to what the function is doing and is acceptable:

- [x] `drawAxes`         
- [x] `drawBarseries`         
- [x] `drawHggroup`         
- [x] `drawImage`      
- [x] `drawLine`         
- [x] `drawPatch`        
- [x] `drawQuiverGroup` 
- [x] `drawScatterPlot`         
- [x] `drawSurface`         
- [x] `drawText`                  
- [x] `drawTextbox`   
- [x] `findLegendInformation`
- [x] `getAxisOptions`         
- [x] `getColorbarOptions`         
- [x] `getLegendOpts`         
- [x] `getMarkerOptions`     
- [x] `getPositionOfText`    
- [x] `handleAllChildren`      
- [x] `legendPosition`   
- [x] `makeTable`        
- [x] `matlab2tikz`      
- [x] `matlabTicks2pgfplotsTicks`         
- [x] `parseTexSubstring`
- [x] `patchcolor2xcolor`         
- [x] `prettyPrint`      
- [x] `saveToFile`         
- [x] `surfaceOpts`         
- [x] `surfaceOptsOfSurf`
- [x] `shaderOptsSurfPatch`
- [x] `translateMarker`         

E.g. `translateMarker` is just a big `switch` statement which essentially translates 15 different marker definitions from MATLAB to TikZ. The code is clear to read, so the complexity is not a major issue (not that we cannot reduce its complexity, but it wouldn't help readability that much).

E.g. in `drawText`, the last part converts a 2D/3D from MATLAB to TikZ and checks whether it lies outside the axis. This code is (almost) duplicated for 2D and 3D and hence could be refactored out into another function.

**Note** If you have checked a certain function, please leave a message (in the code if appropriate and here). You can also check the function above to mark it done.

**Comment by PeterPablo** [comment]
Do you have a final pretty graph?

**Comment by egeerardyn** [comment]
One graph coming up, together with current overview of the complexity scores:

![complexity](https://cloud.githubusercontent.com/assets/177360/7214753/1f5754ae-e5ba-11e4-93aa-9130adc87315.png)


            Function            |Complexity 
--------------------------------|-----------
          `imageAsPNG`          |    10     
      `getPositionOfText`       |    10     
           `getColor`           |    10     
      `patchcolor2xcolor`       |    10     
         `matlab2tikz`          |     9     
       `getMarkerOptions`       |     9     
     `translateMarkerSize`      |     9     
          `drawPatch`           |     9     
        `drawErrorBars`         |     9     
   `matlab2pgfplotsColormap`    |     9     
    `getColorbarPosOptions`     |     9     
   `drawLegendOptionsOfAxes`    |     8     
        `getAxisOptions`        |     8     
         `imageAsTikZ`          |     8     
      `drawFilledContours`      |     8     
    `drawAnnotationsHelper`     |     8     
 `disableClippingInCurrentAxes` |     8     
     `shaderOptsSurfPatch`      |     8     
      `getColorbarOptions`      |     8     
        `getLegendOpts`         |     8     
    `isTickLabelsNecessary`     |     8     
       `rgb2colorliteral`       |     8     
           `printAll`           |     8     
         `prettyPrint`          |     8     
        `parseTexString`        |     8     
          `saveToFile`          |     7     
     `findLegendInfoMATLAB`     |     7     
        `drawGridOfAxes`        |     7     
         `setAxisTicks`         |     7     
           `drawLine`           |     7     
      `setColorsOfPatches`      |     7     
         `drawSurface`          |     7     
    `getScatterOptsOneColor`    |     7     
       `drawQuiverGroup`        |     7     
     `legendEntryAlignment`     |     7     
      `translateLineStyle`      |     7     
          `makeTable`           |     7     
     `getFigureDimensions`      |     7     
         `convertUnits`         |     7     
     `mergeAdjacentTexCmds`     |     7     
     `getAssociatedLegend`      |     6     
       `getTitleOrLabel_`       |     6     
         `getAxisTicks`         |     6     
    `normalizedAlphaValues`     |     6     
     `getXYAlignmentOfText`     |     6     
        `drawHistogram`         |     6     
   `setBarLayoutOfBarSeries`    |     6     
        `drawAreaSeries`        |     6     
       `cdata2colorindex`       |     6     
  `matlabTicks2pgfplotsTicks`   |     6     
     `formatPgfTickLabels`      |     6     
             `join`             |     6     
   `getRelativeAxesPosition`    |     6     
       `matlab2texUnits`        |     6     
       `extractValueUnit`       |     6     
          `fonts2tex`           |     6     
          `formatDim`           |     6     
   `VersionControlIdentifier`   |     6     
        `addStandalone`         |     5     
         `findPlotAxes`         |     5     
        `addCustomCode`         |     5     
    `findLegendInformation`     |     5     
           `drawAxes`           |     5     
`drawBoxAndLineLocationsOfAxes` |     5     
        `handleColorbar`        |     5     
        `writePlotData`         |     5     
        `getLineOptions`        |     5     
         `drawContour`          |     5     
       `drawAnnotations`        |     5     
       `drawVisibleText`        |     5     
   `getRectangleFaceOptions`    |     5     
        `drawBarseries`         |     5     
     `getAndRescaleQuivers`     |     5     
         `getFontStyle`         |     5     
    `getCDataWithFallbacks`     |     5     
     `parseInputsForTable_`     |     5     
         `addChildren`          |     5     
      `parseTexSubstring`       |     5     
      `openFileForOutput`       |     4     
      `isColorDefinitions`      |     4     
     `addLegendInformation`     |     4     
        `isAxisVisible`         |     4     
           `addLabel`           |     4     
       `splitByArraySize`       |     4     
           `setColor`           |     4     
        `getPatchShape`         |     4     
      `addZBufferOptions`       |     4     
          `shaderOpts`          |     4     
       `drawScatterPlot`        |     4     
    `getScatterOptsColormap`    |     4     
     `organizeScatterData`      |     4     
    `drawStemOrStairSeries_`    |     4     
       `getRelevantAxes`        |     4     
    `cellstrOneLinePerCell`     |     4     
         `escapeTildes`         |     4     
       `escapeAmpersands`       |     4     
           `opts_add`           |     4     
         `opts_append`          |     4     
   `opts_append_userdefined`    |     4     
          `opts_copy`           |     4     
        `getEnvironment`        |     4     
         `versionArray`         |     4     
          `isRGBTuple`          |     3     
   `generateColorDefinitions`   |     3     
     `drawBackgroundOfAxes`     |     3     
        `setAxisLimits`         |     3     
      `getXYZDataFromLine`      |     3     
          `plotLine2d`          |     3     
          `drawImage`           |     3     
   `flipImageIfAxesReversed`    |     3     
    `getXYZDataFromSurface`     |     3     
        `drawRectangle`         |     3     
   `getRectangleEdgeOptions`    |     3     
 `shaderOptsSurfPatchEdgeNone`  |     3     
`shaderOptsSurfPatchEdgeInterp` |     3     
 `shaderOptsSurfPatchEdgeFlat`  |     3     
  `shaderOptsSurfPatchEdgeRGB`  |     3     
    `addCDataToScatterData`     |     3     
      `getColorOfMarkers`       |     3     
        `getNumBarAndId`        |     3     
   `pgfplots2matlabColormap`    |     3     
      `legendOrientation`       |     3     
       `addIfNotDefault`        |     3     
      `parseStringsAsMath`      |     3     
          `opts_merge`          |     3     
          `opts_print`          |     3     
         `switchMatOct`         |     3     
  `checkDeprecatedEnvironment`  |     3     
      `filenameValidation`      |     2     
     `filehandleValidation`     |     2     
         `isCellOrChar`         |     2     
       `fileOpenForWrite`       |     2     
         `addComments`          |     2     
       `applyHgTransform`       |     2     
      `add3DOptionsOfAxes`      |     2     
    `retrievePositionOfAxes`    |     2     
            `getTag`            |     2     
   `assertValidAxisSpecifier`   |     2     
      `assertRegularAxes`       |     2     
      `maybeShowInLegend`       |     2     
    `conditionallyCyclePath`    |     2     
     `jumpAtUnboundCoords`      |     2     
    `findStartOfContourData`    |     2     
      `getRotationOfText`       |     2     
        `shaderOptsMesh`        |     2     
  `getOrientationOfBarSeries`   |     2     
      `getFaceColorOfBar`       |     2     
         `drawEllipse`          |     2     
        `drawTextarrow`         |     2     
    `removeSuperfluousTicks`    |     2     
     `dealColorDefinitions`     |     2     
       `getAxesPosition`        |     2     
         `getOrDefault`         |     2     
     `getFactoryOrDefault`      |     2     
           `userInfo`           |     2     
         `userWarning`          |     2     
      `warnAboutParameter`      |     2     
           `pos2dims`           |     2     
           `opts_has`           |     2     
           `opts_get`           |     2     
            `isHG2`             |     2     
        `isVersionBelow`        |     2     
     `needsPgfplotsVersion`     |     2     
    `formatPgfplotsVersion`     |     2     
           `TeXpath`            |     1     
      `setDimensionOfAxes`      |     1     
       `drawTitleOfAxes`        |     1     
           `getTitle`           |     1     
           `getLabel`           |     1     
         `getAxisLabel`         |     1     
           `isAxis3D`           |     1     
          `splitLine`           |     1     
           `drawText`           |     1     
      `getScatterOptsRGB`       |     1     
        `drawStemSeries`        |     1     
       `drawStairSeries`        |     1     
        `linearFunction`        |     1     
       `externalFilename`       |     1     
  `getNaturalFigureDimension`   |     1     
       `escapeCharacters`       |     1     
            `isNone`            |     1     
      `getAndCheckDefault`      |     1     
          `isVisible`           |     1     
           `opts_new`           |     1     
         `opts_remove`          |     1     
   `errorUnknownEnvironment`    |     1     
           **Total**            |    796

**Comment by PeterPablo** [comment]
Great! This :+1: is for you and your commitment to this task!

**Comment by egeerardyn** [comment]
Thanks. In any case: next similar challenge will be #566. 
First step, I think will be to physically cluster the different call chains together when possible (e.g. `drawStemSeries` and `drawStairSeries` are the only ones calling `drawStemOrStairSeries_` so they should all be quite close in the code). But that's something for after the 1.0 release.
