### ISSUE TITLE
cleanfigure / detecting partly visible lines

### ISSUE THREAD

**Issue by cpc-pk** [matlab2tikz/matlab2tikz#392]
Applying cleanfigure() made disappear some lines completely from my plots. I created teh following minimal example:
plot([2 2 3 3 4 4]-.5,[2 6 2 6 2 6]); axis([1 4 1 4]);
![orig](https://cloud.githubusercontent.com/assets/503455/4843966/a2023c38-6037-11e4-942b-5fbc77746c85.png)
I briefly looked into the code and thought cleanfigure() would try to find out whether parts of the connecting lines are visible or not. However, apparently it crops all but the first two points.
![cleaned](https://cloud.githubusercontent.com/assets/503455/4843975/c9661c86-6037-11e4-8a01-b7e05d451800.png)

**Comment by PeterPablo** [comment]
I was successful in recreating the described issue. Key is to further reduce the visible axis so points lay outside the axis both below and above:
```
plot([2 2 3 3 4 4]-.5,[2 6 2 6 2 6]);
axis([1 4 2.5 4]);
cleanfigure();
```
The call of `cleanfigure()` currently removes all points, because additional `NaN` are added. I am working on a fix. This is closely related to #400.

**Comment by PeterPablo** [comment]
This is fixed by https://github.com/matlab2tikz/matlab2tikz/pull/531.
![image](https://cloud.githubusercontent.com/assets/4340267/6379753/df725f12-bd34-11e4-9741-f140397e2de3.png)
