### ISSUE TITLE
[ACID(20)]moreLegends has overlapping legend entries

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#399]
ACID(21) moreLegends fails to properly position the legends ("Sine" overlapps "Cosine"). Screenshot from MATLAB 2014b. 2014a gives identical results.
![image](https://cloud.githubusercontent.com/assets/4340267/4883734/f048d548-6364-11e4-885b-9380bfe340ec.png)

**Comment by PeterPablo** [comment]
Still present, but now this is `ACID(20)`.

**Comment by okomarov** [comment]
I did some investigation time ago, and in brief it is NOT possible with current pgfplots to implement it. 

When we parse the first axis, we won't find the cosine line at all! We would basically need to add the line from the second axis to the first, make it invisible, but still include it in the legend and exclude l;egend generation for second axis....

**Comment by PeterPablo** [comment]
Legendentry `cosine` is still missing with 68cc381 on HG2 :-(

**Comment by okomarov** [comment]
Yes, expected. Transition towards a proper implementation of legends with plotyy. Anyways, cosine label was not visible.

**Comment by PeterPablo** [comment]
True. I almost closed here, since you indicated this as fixed in #760, though wanted to verify this myself before closing.

**Comment by okomarov** [comment]
fixed in #773
