### ISSUE TITLE
[ACID(22)] zoom fails

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#400]
ACID(22) zoom fails, since horizontal and vertical line are not plotted. Screenshot shows output from MATLAB 2014b. 2014a gives identical results.
![image](https://cloud.githubusercontent.com/assets/4340267/4883746/292db126-6365-11e4-87d5-aa8bda0296b8.png)

**Comment by PeterPablo** [comment]
This also affects `ACID(47) zplanePlot1` is fixed by https://github.com/matlab2tikz/matlab2tikz/issues/531.

![image](https://cloud.githubusercontent.com/assets/4340267/6379690/75252482-bd34-11e4-9b9b-5e8d3a8ec39b.png)

**Comment by egeerardyn** [comment]
This should be fixed by #531 / #547.
