### ISSUE TITLE
Bar width in axis units

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#443]
Since `pgfplots 1.7`, the bar width of a bar plot can be specified in axis units. We should prefer this over absolute units, as axis units would allow the figure to scale better.
Probably, MATLAB also uses those axis units somewhere, so this shouldn't be too had to implement.
We should, however, set the `needsPgfVersion` when we set the bar width if we implement this feature request.

**Comment by PeterPablo** [comment]
Fixed by PR #503.
