### ISSUE TITLE
Contour plots not working

### ISSUE THREAD

**Issue by JamesMathews** [matlab2tikz/matlab2tikz#462]
I am currently trying to create a 2 dimensional contour plot a function, with the Matlab Code being along the lines of 

``` matlab
theta=pi;
[r,z]=meshgrid(5:0.5:15,-20:1:20);
h=real(pressureserratedcorr(r,theta,z));
contourf(-r*cos(theta),z,h); %Projection onto x-axis
pcolor(-r*cos(theta),z,h);  %Projection onto x-axis
shading interp;
```

(I know this might not be the best way of doing it). This works fine but I have come across a function which when exporting from Matlab does not copy over the function values, i.e it just records the (r, theta ,z) coordinates and not the function value. 

This is the matlab2tikz code it is creating

``` latex
\addplot3[%
surf,
shader=interp,
z buffer=sort,
colormap/jet,
mesh/rows=29]
table[row sep=crcr,header=false] {%
%
4.40152785589604    -20 0\\
4.37337288373661    -19.715 0\\
4.34601310540075    -19.43  0\\
…
```

And this is what it should look like

``` latex
\addplot3[%
surf,
shader=interp,
z buffer=sort,
colormap/jet,
point meta=explicit,
mesh/rows=29]
table[row sep=crcr,header=false,meta index=3] {%
%
4.40152785589604    -20 0   -0.0885707249283333\\
4.37337288373661    -19.715 0   -0.0871986959840821\\
4.34601310540075    -19.43  0   -0.085503922724335\\
…
```

Only difference is the function. I can give the function that works and that doesn't and full files if needed. Tested on another computer and produces same result. Any ideas would be welcome!

James

**Comment by BounharAbdelaziz** [comment]
Hi, I am facing the same problem with R2022a :(
