### ISSUE TITLE
ACID test 37 errorBars2 fails in octave (works in MATLAB)

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#516]
... because data file `myCount.dat` could not be found, though present in folder `private`. Tested in ocatave 3.8.2. It works properly in MATLAB.

```
octave:7> addpath(genpath("~/matlab/0_addons/"))
octave:8> ACID(37)
error: load: unable to find file myCount.dat
error: called from:
error:   /home/.../matlab/0_addons/figures/matlab2tikz/test/suites/ACID.m at line 832, column 8
error:   /home/.../matlab/0_addons/figures/matlab2tikz/test/suites/ACID.m at line 146, column 14
octave:8> version
ans = 3.8.2
```

An additional call `addpath(genpath("~/matlab/0_addons/figures/matlab2tikz/test/suites/private"))` makes the data file discoverable:
```
octave:11> ACID(37)
warning: load: file found in load path
ans =

  scalar structure containing the fields:

    description = Another error bar example.
    function = errorBars2
```

**Comment by PeterPablo** [comment]
Thank you for the pointer! Please go ahead and close this issue, once PR #485 is merged.

**Comment by PeterPablo** [comment]
This also needs to be considered, when somebody stars working on issue #414 (#368 is related).

**Comment by PeterPablo** [comment]
I meant to note that the handling of the search path needs to be considered, when #414 is tackled since creation of lookup-tables in data files is problematic, if they are placed in the `private` folder.

**Comment by egeerardyn** [comment]
@PeterPablo That's true. But I think it would be better to internalize such a LUT anyway. For compatibility, ASCII-encoding is recommended anyway, so the difference between writing it in code or out to a file is negligible what storage concerns. And having to read a file ourselves only adds complexity IMHO.

**Comment by PeterPablo** [comment]
Agreed! Further discussion concerning testcase data in general should be continued in #414.

**Comment by PeterPablo** [comment]
@egeerardyn, would you mind applying your commit https://github.com/matlab2tikz/matlab2tikz/commit/f5c9d31fadd915d4cda7c169a1c94fc5056c4ecd to the `develop` branch? This should make the testsuite `ACID` executable from octave without manual interference, once my two open pull requests are merged.

**Comment by egeerardyn** [comment]
@PeterPablo: there you go :smile: .

For such small stuff, you can always use the `git cherry-pick` command (which like a mini rebase, or actually the other way around: a rebase is a succession of cherry-picks). I guess this fixes that issue, if this is not the case, please reopen this issue.

**Comment by PeterPablo** [comment]
@egeerardyn: Thank you! I know that I can do this locally but think this might be useful especially for @okomarov, since he also started testing against octave and it is quite cumbersome to manually edit files...
