### ISSUE TITLE
[R2014b] histogram

### ISSUE THREAD

**Issue by saerdnah** [matlab2tikz/matlab2tikz#525]
When trying to save (master + develop ; both show the same error) a plot generated by the new function histogram [1] the following error output is generated:

Error using matlab2tikz>handleAllChildren (line 692)
I don't know how to handle this object: histogram

[1]  http://de.mathworks.com/help/matlab/ref/histogram.html

**Comment by okomarov** [comment]
@matlab2tikz/developers Shall we go for `histogram` from the `\usepgfplotslibrary[statistics]` and external .dat file with all data points or produce a `bar` plot?

**Comment by PeterPablo** [comment]
Fixed by https://github.com/matlab2tikz/matlab2tikz/commit/6095ed9caa6597bbdfd0f8eeb21d651738ada656. Thanks to @okomarov!
