### ISSUE TITLE
plotyy coloring of right axis

### ISSUE THREAD

**Issue by mklauco** [matlab2tikz/matlab2tikz#539]
figure created by `plotyy()` in matlab, has right axis green (or whatever is specified by `set()` command), but exported tikz is ignoring this setting and the resulting figure loaded in latex has both left and right axis blue.

I'm attaching code:
```matlab
tikz_options = ['ylabel style={font=\scriptsize},',...
                'xlabel style={font=\scriptsize},',...
                'xticklabel style={font=\scriptsize},'...
                'yticklabel style={font=\scriptsize},'...
                'legend style={font=\scriptsize}'];

figure
[ax, p1, p2] = plotyy(1:10, [1:10].^2, 1:10, 2*[1:10],'plot','plot');
matlab2tikz('file.tikz', 'height', '\figureheight',...
    'width', '\figurewidth', 'parseStrings', false,...
    'extraaxisoptions', tikz_options);
```

![2015-01-29_103606](https://cloud.githubusercontent.com/assets/10755273/5955393/af29d5ee-a7a2-11e4-8cf5-43fe682cbbdd.png)

I'm using Matlab 2014a, and same result I get on R2013b or R2014b.

**Comment by okomarov** [comment]
@mklauco This problem (order in which axes are processed) has been fixed in the developing branch and will be part of the next release. If you cannot wait, please update your version to the developing branch.
