### ISSUE TITLE
Testing from any directory

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#543]
When the testing functions are called from within any directory (so not `./test`), some things may fail as reported in #485.

We should provide some measures to deal with this (or at least throw a dev-friendly exception).

**Comment by PeterPablo** [comment]
I propose one possible approach: If `pwd` returns a path with `matlab2tikz` in it, change the folder using `cd` in an appropriate way, then run the tests. We can even return to the previous path after executing the tests.

**Comment by egeerardyn** [comment]
Seems a reasonable approach to me, however, we have to make sure that in case of an exception the same behavior is observed.

**Comment by PeterPablo** [comment]
Just had another idea:
`which('matlab2tikz')` returns the path to `matlab2tikz.m`. We can as such easily change to the correct folder in a deterministic way.

**Comment by egeerardyn** [comment]
This has been incorporated in #485
