### ISSUE TITLE
Pgfplots 1.12 incompatible with matlab2tikz('externalData',true)

### ISSUE THREAD

**Issue by andreas12345** [matlab2tikz/matlab2tikz#548]
When used with externalData=true, matlab2tikz 0.6.0 generates code with the table option "row sep=crcr":
```
\addplot [color=black,solid]
table[row sep=crcr]{\relativepath /test-1.tsv};
```
This is not compatible with Pgfplots 1.12 (see http://ctanhg.scharrer-online.de/hg/pgfplots/rev/54e8d4404680), compilation fails with the message:
```
! Package pgfplots Error: Sorry, the choice 'row sep=crcr' is currently only available for inline tables, not for external files.
```
The solution is to remove [row sep=crcr], which did not make sense for external data files anyway.

Also see: #451

**Comment by egeerardyn** [comment]
I will look into this tonight.

**Comment by PeterPablo** [comment]
@andreas12345 This should be fixed in current `develop`. Please give it a try. If this is not fixed, we can reopen this issue.

**Comment by andreas12345** [comment]
Awesome, thanks for fixing this so quickly!
