### ISSUE TITLE
Wiki page contributing is outdated

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#558]
https://github.com/matlab2tikz/matlab2tikz/wiki/Contribute needs to be adapted to reflect the changes concerning the test environment: `testGraphical(...)` and `testHeadless(...)`

I need to leave now, so can not do this myself.

**Comment by egeerardyn** [comment]
Done. I've mostly linked to the testing README or some parts that should be inferred from the code anyway. That way, it is less likely that the wiki page and the code diverge further.
