### ISSUE TITLE
Recheck hashes

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#579]
As reported in #578 (or egeerardyn/matlab2tikz@c184d2a6cc51d8d46d1c9be0ab589cde715077ed in specific) there was a recent problem with one of the R2014b hashes.
At that time, I ran a bisection on the violating range. But to be honest, I think this has to be rechecked due to possible persistent variables in the hash checking.

The output of my bisection (with some minor tweaks to display well on GitHub) was:
> Last login: Sun Mar 15 13:54:38 on ttys004
>  egon@Egon-MB : m2t : ➦ 1ea5b26 : git bisect start
>  egon@Egon-MB : m2t : ➦ 1ea5b26 (bisect) : git bisect good
>  egon@Egon-MB : m2t : ➦ 1ea5b26 (bisect) : git bisect bad develop
> Bisecting: 31 revisions left to test after this (roughly 5 steps)
> [38f894f35549800ed9a48459a52c4267bfe8e612] Extract `draw{Edge,Face}OfRactangle`
>  egon@Egon-MB : m2t : ➦ 38f894f (bisect) : git bisect bad
> Bisecting: 15 revisions left to test after this (roughly 4 steps)
> [5118cd117c787e6f1f71e9e8430d4d1b8acf56fd] Check for malformed input in getColor->image
>  egon@Egon-MB : m2t : ➦ 5118cd1 (bisect) : git bisect good
> Bisecting: 7 revisions left to test after this (roughly 3 steps)
> [2c205fcde5202644c899157b5ea92d76dbf3c229] Extract `isRGBVector` from `getColor`
>  egon@Egon-MB : m2t : ➦ 2c205fc (bisect) : git bisect bad
> Bisecting: 3 revisions left to test after this (roughly 2 steps)
> [ba57b34e48aaf0c629cdf24b4a94af7647f8e7bf] move single line
>  egon@Egon-MB : m2t : ➦ ba57b34 (bisect) : git bisect good
> Bisecting: 2 revisions left to test after this (roughly 1 step)
> [c1112067dfc756a51a70ef18203ae4c33e9a32e1] Merge pull request # 559 from PeterPablo/travis_ensure_paging_screen_output
>  egon@Egon-MB : m2t : ➦ c111206 (bisect) : git bisect good
> Bisecting: 0 revisions left to test after this (roughly 1 step)
> [eb145da12577b567c2c5b12a74de0d747f67dad8] Merge branch 'fix-alpha' into develop
>  egon@Egon-MB : m2t : ➦ eb145da (bisect) : git bisect bad
> Bisecting: 0 revisions left to test after this (roughly 0 steps)
> [5dcbe711c62a86912049513a57ea1d32466d2884] Also test inteer alpha channels
>  egon@Egon-MB : m2t : ➦ 5dcbe71 (bisect) : git bisect bad
> **5dcbe711c62a86912049513a57ea1d32466d2884 is the first bad commit**
> commit 5dcbe711c62a86912049513a57ea1d32466d2884
> Author: Egon Geerardyn <egon.geerardyn@gmail.com>
> Date:   Sat Mar 7 17:02:04 2015 +0100
> 
>     Also test inteer alpha channels
> 
>     TikZ output looks fine in all 3 envs.
>     However, with `pgfplots 1.12` and LuaLaTeX` the output looks a bit off.
>     LaTeX doesn't suffer the same problem.
> 
> :040000 040000 f837edb4d85f8a29845616258eb95592023e5df6 316f2c5696adee15d4eece7a6510095dbb541d73 M    test
>  egon@Egon-MB : m2t : develop (bisect) : git co 5dcbe711c62a86912049513a57ea1d32466d2884^
> Note: checking out '5dcbe711c62a86912049513a57ea1d32466d2884^'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b new_branch_name
> 
> HEAD is now at 5118cd1... Check for malformed input in getColor->image
>  egon@Egon-MB : m2t : ➦ 5118cd1 (bisect) : git bisect reset
> Previous HEAD position was 5118cd1... Check for malformed input in getColor->image
> HEAD is now at 1ea5b26... Merge pull request #485 from egeerardyn/unify-test-harness
>  egon@Egon-MB : m2t : ➦ 1ea5b26 : cd test
>  egon@Egon-MB : m2t/test : ➦ 1ea5b26 : wdiff data/converted/test86-converted.tex ~/Desktop/test86-converted.tex
> ```diff
> % This file was created by matlab2tikz.
> %
> \documentclass[tikz]{standalone}
> \usepackage{pgfplots}
> \usepackage{grffile}
> \pgfplotsset{compat=newest}
> \usetikzlibrary{plotmarks}
> \usepgfplotslibrary{patchplots}
> \usepackage{amsmath}
> 
> \begin{document}
> \begin{tikzpicture}
> 
> \begin{axis}[%
> width=0.95092\figurewidth,
> -height=\figureheight,
> -at={(0\figurewidth,0\figureheight)},
> +height=0.418605\figureheight,
> +at={(0\figurewidth,0.581395\figureheight)},
> scale only axis,
> axis on top,
> xmin=     0.5,
> xmax=    20.5,
> y dir=reverse,
> ymin=     0.5,
> ymax=    20.5,
> axis background/.style={fill=white}
> ]
> \addplot [forget plot] graphics [xmin=     0.5,xmax=    20.5,ymin=     0.5,ymax=    20.5] {test86-converted-1.png};
> \end{axis}
> 
> +\begin{axis}[%
> +width=0.95092\figurewidth,
> +height=0.418605\figureheight,
> +at={(0\figurewidth,0\figureheight)},
> +scale only axis,
> +axis on top,
> +xmin=     0.5,
> +xmax=     2.5,
> +ymin=     0.5,
> +ymax=     2.5,
> +axis background/.style={fill=white},
> +title style={font=\bfseries},
> +title={Integer Alpha Data},
> +axis x line*=bottom,
> +axis y line*=left
> +]
> +\addplot [color=black,solid,line width=2.0pt,forget plot]
> +  table[row sep=crcr]{%
> +     0.5         0.5\\
> +     2.5         2.5\\
> +};
> +\addplot [color=black,solid,line width=2.0pt,forget plot]
> +  table[row sep=crcr]{%
> +     0.5         2.5\\
> +     2.5         0.5\\
> +};
> +\addplot [forget plot] graphics [xmin=     0.5,xmax=     2.5,ymin=     0.5,ymax=     2.5] {test86-converted-2.png};
> +\end{axis}
> \end{tikzpicture}%
> \end{document}%
> ```

**Comment by PeterPablo** [comment]
My guess: Introducing subplots changes the behavior of how `width` and `height` are determined. That commit 5dcbe711c62a86912049513a57ea1d32466d2884 did introduce an additional subplot.

**Comment by egeerardyn** [comment]
Well, I'm not 100% convinced that the subplot is still there. But I haven't taken the time to look at this in more detail. This issue report is just a reminder that we should have a proper look.

**Comment by egeerardyn** [comment]
The problem was probably that I still had some hashes loaded persistently into the table. I will open a new issue to prevent such behavior in the future.
