### ISSUE TITLE
Implement Semantic Versioning

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#583]
[Semantic Versioning](http://www.semver.org) is an understandable way to designate a version number. Briefly:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

Our 1.0 release is way overdue, so this is an ideal time to adhere to this "standard" in the future. It will mean our version numbers will increase at a higher pace than currently (but that's not a bad thing).

**Comment by okomarov** [comment]
Should the next release be then 1.0.0? 
Is there an easy way to count number of patches, minor and major mods applied when closing issues and merging PR?

**Comment by PeterPablo** [comment]
Fine by me to bump the version. Since API should not change right afterwards, I think that especially #471 (filename/filehandle) should be dealt with and the new simplification algorithm #571 introduced.
@okomarov -- you can see the number of commits between tags and e.g. a branch: [example](https://github.com/matlab2tikz/matlab2tikz/compare/0.6.0...develop)

**Comment by nschloe** [comment]
> Since API should not change right afterwards

I wouldn't mind bumping to 2.* for the next release. Otherwise, we'll never catch up with Chrome.
For the release, I thought I'll definitely wait for #571 and #560. If there's #471 on top, fine.

**Comment by egeerardyn** [comment]
@okomarov 
> Is there an easy way to count number of patches, minor and major mods applied when closing issues and merging PR?

Not that I'm aware of. That's a really good point you bring up. I suggest we have non-firm numbers in the `develop` branch and regularly check for the amount of features that have changed. While our current releases are quite far apart (a few months) and contain a lot of new things, maybe we can just release more minor versions i.e. after each $smallNumberOf PRs, we have a release PR (i.e. merge `develop` back into `master`) with a bumped version number, change log added, etc.

@okomarov @PeterPablo @nschloe 
With regard to #471 and deprecating old features, that is explicitly mentioned in [SemVer](http://semver.org) (emphasis mine):

> #### How should I handle deprecating functionality?
>
> Deprecating existing functionality is a normal part of software development and is often required to make forward progress. When you deprecate part of your public API, you should do two things: (1) update your documentation to let users know about the change, (2) **issue a new minor release with the deprecation in place**. Before you **completely remove the functionality in a new major release** there should be at least one minor release that contains the deprecation so that users can smoothly transition to the new API.

That is similar to our current approach: first deprecate it in a release, afterwards remove it in a future release. Only now, we can have a clear moment when such changes are introduced (i.e. at a major release instead of just "a future release"). For this feature, removing the old syntax would be in version 2.0. Since we're not using a rigid version number right now, it doesn't matter whether we add the new syntax right now in 1.0 or 1.1 (or even later).

At the moment, I've scheduled #471 in the 1.1 milestone (i.e. deprecation of the old syntax and introduction of the new syntax which should be backwards compatible, hence minor releas), to make sure we get everything right for our first major release (i.e. 1.0). If we can thoroughly test that within 2 weeks of time, for me it's also fine to include it already in 1.0.

I've added the issues I'd like to see addressed in [1.0 to a milestone](https://github.com/matlab2tikz/matlab2tikz/milestones/1.0%20Release).

**Comment by okomarov** [comment]
How about we create labels 0.0.1 and 0.1.0. Then we could query in the issue search box `closed:>2015-01-01 label:0.0.1`, count and list?

**Comment by egeerardyn** [comment]
@okomarov I think that will lead to a lot of labels (e.g. `1.0.0`, `1.0.1`, ...) that are quite short-lived. Unless you mean we could create labels `+patch-version`, `+minor-version`, `+major-version` to indicate that a PR/issue requires a bump in each of these version numbers? That would be a really great idea.

Luckily, there's no need to count those per release: either the major/minor or patch version is increased (and the lower levels are reset to 0) with a new release. We shouldn't bump the minor part with multiple units (even if we include 2 new `+minor-version` PRs) in a single release.

For making the change log, this information is interesting, but we can essentially get it from `git` itself using `git log START..STOP` (or from the github interface). This gives information at a commit level, but can probably be processed as a graph as well (i.e. at a PR/feature level).

**Comment by okomarov** [comment]
@egeerardyn No, I meant just two labels, `0.0.1` for +patch-version (I think the numeric reads faster) and `0.1.0` for the minor (and I see that we need a major one too)

I was/am probably thinking of a different release approach that happens at ~fixed time intervals, e.g. every 6 months (like Matlab), where labels play a counting and additive role. However, since you suggest that the actual version number does not get bumped with multiple units, they will just be useful to identifying what has been done over the time lapse. 
I think this is useful since `git log START..STOP` with hundreds of commits is less informative than say a count of twelve `0.0.1` (with relevant issue/PR names) and four `0.1.0` for deciding if it is time to release a new version. 

The drawback, we would need to label almost everytime.

**Comment by egeerardyn** [comment]
I like the idea of adding such a label to the issues. I don't think it's really a problem to have to label every issue/PR because it conveys useful information. I wil do that right away.

**With respect to release cycle:**
Development progress should dictate the release cycle, not the passing of time. I think it's not realistic to let time dictate everything, since our development effort varies a lot over time. Also, it detracts from the important thing: quality and user satisfaction.

Most of the projects that I've used with a fixed release cycle (Ubuntu, Mac OS X, MATLAB, ...) impose major changes in tiny amounts of time and the torrent of problems at those fixed amounts of time (e.g. for [Ubuntu](https://www.google.com/trends/explore#q=ubuntu%20broken%2C%20ubuntu%20bug%2C%20ubuntu%20problem%2C%20ubuntu%20release&cmpt=q&tz=) you can clearly see their April and October releases spike). Smaller release avoid such spikes and IMHO those spikes are why users typically are afraid to upgrade their software: it might be a worse experience than before.

Let's just release when we have something that works well, not because "x months have passed since our last release".

**Comment by okomarov** [comment]
:+1: 
I agree on releasing when there is good work to show for.

**Comment by egeerardyn** [comment]
I've added the different labels. I've named them `+1.0.0` (major bump), `+0.1.0` (minor bump), `+0.0.1` (patch) and I've added another one `+0.0.0` that should be attached to issues that do not warrant a version bump (e.g. this very issue).

That last `+0.0.0` label is needed to know that when an issue doesn't have such a label added, it's not correctly labeled to be merged.

**Comment by okomarov** [comment]
I would avoid tagging everything, because the categories of everything that is not a bump are just too many (and the 0.0.0 feels redudant): discussions, workaround exists, closed because not relevant, not a priority etc... 

I am pretty sure that relevant things, that cause a PR directly or indirectly, will be labelled sooner or later.

**Comment by egeerardyn** [comment]
@okomarov Perhaps you're right. Now I think of it, most things that are `+0.0.0` are probably also tagged `development` (i.e. not user-facing and hence not relevant for version bumping or at most patches). I will remove the tag.
