### ISSUE TITLE
Updater should be more verbose

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#584]
The updater should be more verbose towards the user, more specifically.

 - [x] before upgrading to another major version (see #583 and [Semantic Versioning](http://www.semver.org)) the user should be warned about the practical implications (i.e. some parameters may not work anymore or do different things than before)
 - [x] before an upgrade, show the change log (preferably just the relevant part of it)
 - [x] show a message on how to disable updating (if we don't do so already)
 - [x] :new: check for upgrades after conversion (possibly in an `onCleanup` construct to allow for patches in case an error is introduced)
 - ? :new: perhaps we should add a parameter `installUpdates` that allows to choose whether an update should be carried out. If the update is disallowed, we should just display a message and maybe even the changelog. Possible values would be:
    * `'major'` (or `'yes'`): major (and minor and patch) versions are installed automatically
    * `'minor'`: minor (and patch) versions are installed automatically 
    * `'patch'`: patch  versions are installed automatically
    * `'ask'`: just show the prompt as we do now (default behavior)
    * `'no'`: don't update automatically

**Comment by egeerardyn** [comment]
Let's put the "auto-install" feature in the fridge. I'm not quite sure there is a lot of demand for that: it would be nice to have from our side, but I'm unsure whether we really need it at the moment.

**Comment by PeterPablo** [comment]
I also think that this isn't any of our *core* competences and from the first implementation tests I remember that implementing this feature is more involved than it seems at first. So let's leave things the way they are for now.

**Comment by PeterPablo** [comment]
Implemented by #697
