### ISSUE TITLE
the sign "| should be in mathmode at least for the y-axis

### ISSUE THREAD

**Issue by 01ivi3r** [matlab2tikz/matlab2tikz#587]
There may be a trick that I did not find but this example gives me the sign "|" in the wrong orientation
```
%Matlab
figure, plot([1:10],[1:10])
ylabel('|abs|')
matlab2tikz('myplot.tex')
```

```
%Latex
\documentclass{article}
\usepackage{pgfplots}
\usepackage{tikz}
\begin{document}
\begin{figure}
\input{myplot.tex}
\end{figure}
\end{document} 
```

**Comment by PeterPablo** [comment]
Hi @01ivi3r,
thank you for your report with a testable example. I will have a look shortly and report back. Did you try with the current `develop` version? ([downloadable here](https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip) as a zip).

**Comment by 01ivi3r** [comment]
Hi, @PeterPablo, 
I just checked and yes, this is the same.

**Comment by egeerardyn** [comment]
The only workaround that I know is to set the labels to LaTeX mode, but then you need to specify the label as a valid LaTeX string.

```matlab
set(ylabel('$|abs|$'), 'interpreter', 'latex')
```

**Comment by 01ivi3r** [comment]
@egeerardyn 
Thank you for your solution, sorry for my bad click!

**Comment by PeterPablo** [comment]
Let's keep this open. We already convert some special characters so that LaTex compiles fine. I will do the same here.

**Comment by egeerardyn** [comment]
@01ivi3r : No problem (those buttons are dangerously close). As @PeterPablo said: we have similar things for other characters in normal `TeX` mode, so this shouldn't be too hard to handle this as well.

**Comment by PeterPablo** [comment]
Before patching this, I'd like to ask for your opinion. As described [here](http://stackoverflow.com/questions/3487966/how-to-insert-pipe-symbol-in-tex), the `|` is typeset correctly, when `\usepackage[T1]{fontenc}` is used in the preamble. Since we can not guarantee this (apart if option `standalone` is set `true`), we probably should go with `\text{\textbar}`.

Should we set the font encoding explicitly in our `standalone` output anyhow?

**Comment by egeerardyn** [comment]
If we don't set the font encoding already, we should.

I think `$|$` is the most comprehensible in TeX mode. What do you think?

Also, I think this problem occurs even with T1 font encoding (I have observed the bug before, and I think I have T1 set in almost all my documents).

**Comment by PeterPablo** [comment]
I will create a PR that adds `$|$`, when the `interpreter` is `tex` (default) and furthermore adds the T1 font encoding to `standalone` output.

**Comment by PeterPablo** [comment]
@01ivi3r, please try again. This should be fixed in the develop version. Please reopen, if you still face a problem.
