### ISSUE TITLE
Warning: "unrecognized escape sequence"

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#611]
I get this when running `testHeadless` in octave on windows. This spams the output tremendously. [Here](http://octave.1599824.n4.nabble.com/Oct-File-helo-world-sample-td4657087.html) an explanation for the cause is given and possible solutions.

We should identify the location that causes the warning and fix it.

**Comment by PeterPablo** [comment]
This is due to how I added the path in my windows octave, it seems. I used single `\` instead of `\\` or `/`. Closing.

**Comment by PeterPablo** [comment]
Nope, this is indeed an issue, but not for all ACID tests. It happens e.g. with `testHeadless(81)` (GUI and cli, but only in windows).

**Comment by okomarov** [comment]
Thank you @PeterPablo!!!!!

The problem is in `errorHandler()`, when it `disp_error_message()`, it should be:

```matlab
function disp_error_message(msg)
    stderr = 2;
    % When displaying the error message in MATLAB, all backslashes
    % have to be replaced by two backslashes. This must not, however,
    % be applied constantly as the string that's saved to the LaTeX
    % output must have only one backslash.
    if isMATLAB() || ispc() 
        msg = strrep(msg, '\', '\\');
    end
    fprintf(stderr, msg);
end
```

**Comment by PeterPablo** [comment]
Please be so kind and create a PR :-)
(Unrelated: How long does the testsuite take in your octave? I have the impression that it runs pretty slowly (in my virtual Win 7) -- approx. factor 2.)

**Comment by egeerardyn** [comment]
Now I think of this: is it likely that there are escape sequences (i.e. `\n` instead of a newline character, etc.) in these error messages? I suspect all of them should already be formatted (i.e. replaced by their actual character).

In that case, I think we should always replace backslashes, or maybe even just do `fprintf(stderr, '%s', msg)`?
