### ISSUE TITLE
VM on windows with linux + octave for development

### ISSUE THREAD

**Issue by okomarov** [matlab2tikz/matlab2tikz#618]
I am sick of Win + Octave. I am gonna migrate into VM linux + Octave.

(after experiencing it) No one sane in his mind would prefer the hassle of installing a (buggy) pre-compiled version of Octave on Windows to a Python port...

I need some help in setting a VM on Win at my university. So, no internet on VM (the uni filters mac addresses) but shared (subset of the)  filesystem with Windows. 

Also, alternative solutions are welcome...but no Octave on Windows.

1. Enable PCU virtualization in the BIOS to allow 64bit Virtual Machines (note: https://forums.virtualbox.org/viewtopic.php?f=1&t=62339)
2. Install virtualbox and download the additions: https://www.virtualbox.org/wiki/Downloads
3. Download lubuntu 64bit Image: http://www.osboxes.org/lubuntu/ 

Add: 
```
sudo apt-get install gcc
sudo apt-get install make
```

5. Install Virtual Box Guest additions (https://www.virtualbox.org/manual/ch04.html - 4.2.1.1) and auto-mount (4.3), then add user `sudo adduser xxxxxxx vboxsf`, log off  and log back in

**Comment by PeterPablo** [comment]
What kind of help do you need?

**Comment by egeerardyn** [comment]
I'm willing to help you, I have some experience with VirtualBox, Parallels and a tiny bit with VMWare.
But I think it's quite weird that you don't get internet access on the VM.

**Comment by okomarov** [comment]
I am gonna install VM. I guess I am gonna go with default config for now. What lightweight linux distro should I go?

**Comment by egeerardyn** [comment]
If you don't have any Linux prejudices, I'd go with Ubuntu (that is what's running on Travis). If you have more experience with Linux, I'm quite a big fan of ArchLinux, but that is an order of magnitude harder to get everything to work, while Ubuntu is quite easy and very well-supported.

**Comment by PeterPablo** [comment]
I would also assist in our HipChat. Ubuntu is easy and you find many
answers in Google. I like the xubuntu flavor due to it coming with less
fancy graphics.

**Comment by egeerardyn** [comment]
Perhaps it's indeed best to continue the discussion in HipChat. (But right now I have to go, if you have any issues, don't hesitate to ping me directly).
