### ISSUE TITLE
Ticks (and labels) for bar plots as intervals

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#625]
In bar plots, we could define the ticks as intervals (`x tick label as interval=true` and/or `y tick label as interval=true) in pgfplots such that the labels are put in-between the ticks (centered around the bars), while the ticks indicate the edges of the intervals.

**Comment by okomarov** [comment]
Matlab's default behaviour actually does not have any ticks. What is the advantage of setting ticks as intervals, do you have something specific in mind?

**Comment by egeerardyn** [comment]
Personally, I think those intervals matches the style better, but probably we could remove the actual ticks equally well.

E.g. this is one of the plots that I once made (partially by hand), which I think is a lot nicer than what `matlab2tikz` generated (with ticks and grids running through the middle of the bars instead, which is just plain ugly IMO).

![screen shot 2015-04-21 at 14 31 02](https://cloud.githubusercontent.com/assets/177360/7252218/53c6a688-e833-11e4-8049-f02963ac5014.png)

**Comment by okomarov** [comment]
I reckon we should stick to Matlab's default, and propose a Matlab based solution to place gridpoints as intervals and relocate the labels:

![untitled](https://cloud.githubusercontent.com/assets/3731173/7253172/903486a4-e832-11e4-835d-661374b18c27.png)

```matlab
A = rand(3);

subplot(211)
bar(A)
set(gca,'XGrid','on')
title 'Matlab default'

subplot(212)
bar(A)
set(gca,'XTick',1.5:1:3,'XTickLabel',[],'XGrid','on')
text(1:3,repmat(-0.1,1,3),{'1','2','3'},'Horiz','center')
title 'Custom code'
```

**Comment by egeerardyn** [comment]
I agree with you that we should stick to MATLAB defaults. 
Unfortunately, I am convinced we should not translate specially placed text objects like in your example to the semantic pgfplots equivalent. Closing this FR as a result.
