### ISSUE TITLE
saveHashTable when test is not executed

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#634]
As noted in, e.g. in #605 by @okomarov, how `saveHashTable(status)` behaves when a test is not executed is not exactly as desired. However, given the simple file formats, it is always a feasible approach to manage the hashes by hand.

**Current behavior:**
for each test in the `status` array, write out the computed hash value to the file unless the test doesn't have a computed hash value (e.g. skipped tests, empty output, ...).

Downsides are:
 - skipped tests (e.g. due to missing toolboxes) have to be handled by hand
 - omitted tests (i.e. ones explicitly not executed) also have to be handled by hand

**What I'd propose instead:**
- first read in the existing hash table
- for each executed test in the `status` array, write out the hash
- for skipped tests, just retain the old hash and issue a warning

That would get rid of the first downside. The second downside, IMHO, is necessary to also handle the case when we remove test cases. To handle that more cleanly, we could always add a flag to `saveHashTable` to, either:
 - remove tests not found in `status` (i.e. current behavior and needed for removal of tests)
 - to retain hashes in the file that have not been specified in `status` (i.e. useful when only a part of the tests has been executed to generate `status`)

**Comment by PeterPablo** [comment]
I agree with your proposal to introduce a flag, who's default will retain hashes.
(I updated your post to finish the sentence in the parenthesis of your second last bullet point.)

**Comment by okomarov** [comment]
I thought again about it and I think we might add an `updateHashTable()` and kepp the save function with overwrite funcionality.

**Comment by egeerardyn** [comment]
Fixed in #720.
