### ISSUE TITLE
`develop` fails on ACID test 58

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#636]
`ACID(58)` fails to compile (tested on R2014(a|b and octave) with 0505932c0ad59f72fb775487ccbbc6a2d2af901f:

Tex code: https://gist.github.com/PeterPablo/d18d2e71f5a125ce1d8c

Who wants to dig?

**Comment by egeerardyn** [comment]
Here the TeX code you provided does not fail to compile using `pdflatex`, `lualatex` and `xelatex`.

I also don't get any problem with generating the TeX code using R2014b or R2014a.

Can you re-check and provide your environment (version of pgfplots, tikz, LaTeX compiler) and the resulting log file? To retrieve the version of `pgfplots` and stuff, please have a look in the generated acid.pdf or acid.tex files.

I have 
```
TikZ 2013/12/13 v3.0.0 (rcs-revision 1.142) 
Pgfplots 2015/01/31 v1.12 Data Visualization (1.12)
```

**Comment by PeterPablo** [comment]
```
This is LuaTeX, Version beta-0.70.2-2012062323 (TeX Live 2012/Debian)
Package: tikz 2013/12/13 v3.0.0 (rcs-revision 1.142)
Package: pgfplots 2014/08/04 v1.11 Data Visualization (1.11-3-g4c99d7a)
```
Log output: https://gist.github.com/PeterPablo/1e22769678fe04c550ea

I will do some quick research and edit my comment, once I find the cause.
