### ISSUE TITLE
`develop` fails on ACID test 69

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#637]
`testGraphical(69)` latexmath2 fails on R2014a, because `cleanfigure` removes the complete figure content on 0505932.

R2014b is fine.

**Comment by egeerardyn** [comment]
Those things can go into the 1.0 release milestone: we should not release when we still have such issues.

**Comment by PeterPablo** [comment]
Agreed.

**Comment by PeterPablo** [comment]
I wonder why you didn't see those issues when compiling the PDFs in your last PR?!

**Comment by egeerardyn** [comment]
I think I know the problem. I ran the tests at the end of last week, I did indeed see an empty output, but in those cases I typically remove the converted plot (i.e. only the right one) in the overview. But it's only late Sunday night that I looked at those outputs again and uploaded them. I went over the output without noticing anything off.
So please accept my humble excuses for this mess.

**Comment by PeterPablo** [comment]
Don't worry. We jointly want to celebrate the 1.0 release so more eyeballs are needed to catch the remaining flaws.

**Comment by PeterPablo** [comment]
Fix is at #639. Please test `ACID(69)`.
