### ISSUE TITLE
Passing different "Extra axis options" to subplots 

### ISSUE THREAD

**Issue by farouqM** [matlab2tikz/matlab2tikz#640]
When a Matlab figure contains subplots, matlab2tikz has sometimes a problem reducing the correct xticks for example. This can be overcome in case of a simple figure  (one subplot) using the "ExtraAxisOptions" which make it easy to do the correction only one time. 
The issue raises when the figure contains multiple subplots with different axis options required. Is there any way to let Matlab2tikz take this into consideration?

**Comment by egeerardyn** [comment]
Anyhow, there is currently no extension of `extraAxisOptions` to be specific for different subplots. Currently we don't have a plan of attack for these kinds of additional options (see also #393 which is very related).

However, if you specify the ticks by hand (or do `set(gca,'XTickMode','manual')` for every axis and and similarly for Y and Z), `matlab2tikz` should carry them over to the output.

Another work-around (documented more elaborately in #393) is to export the figure with the `'externalData', true` option set. Then you edit the produced file `figure.tex` by hand. If you ever have to change the actual data, you can execute `m2t` again using the same options. By then using the old `figure.tex` and the new data files, the lay-out is retained but the data is updated.

If this doesn't answer your question, please provide a minimal working example (i.e. small MATLAB code to generate a figure and preferably a picture to illustrate what is going wrong or what you would expect it to look like). That makes the discussion easier.

**Comment by egeerardyn** [comment]
Closing this issue since there has been no response, so I guess this issue is resolved (or to be resolved by #393).
