### ISSUE TITLE
stackedBarsWithOther (ACID(94)) is missing legend labels

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#648]
on HG1 only; HG2 and octave are not affected
tested on 7a6b248655f555c1411e7397e47bfa3e50eb8050
![image](https://cloud.githubusercontent.com/assets/4340267/7533072/7163d2b8-f56e-11e4-8d73-15f82b055098.png)

**edit:** Legend is also missing in test 35 `xAxisReversed` and test 42 `bodeplots`.

**Comment by egeerardyn** [comment]
I can only reproduce this in HG1; HG2 is fine here.

**Comment by PeterPablo** [comment]
Let me double check HG2. Will edit shortly.

**Comment by PeterPablo** [comment]
Fix is at #667. Two more tests are affected. I updated the first post.
