### ISSUE TITLE
ACID(66) won't compile with lualatex, but works with pdflatex

### ISSUE THREAD

**Issue by PeterPablo** [matlab2tikz/matlab2tikz#661]
```
% This file was created by matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\begin{tikzpicture}

\begin{axis}[%
width=4.525in,
height=3.569in,
at={(0.759in,0.482in)},
scale only axis,
xmin=0,
xmax=6,
ymin=-1,
ymax=1,
axis background/.style={fill=white}
]
\addplot [color=blue,solid,forget plot]
  table[row sep=crcr]{%
0	0\\
1	0.841470984807897\\
2	0.909297426825682\\
3	0.141120008059867\\
4	-0.756802495307928\\
5	-0.958924274663138\\
6	-0.279415498198926\\
};
\node[left, align=right, text=black]
at (axis cs:5.75,0.598) {Each cell is a quoted string\\You can specify how the string is aligned\\$\text{You can use LaTeX symbols like }\pi\text{ }\chi\text{ }\Xi$\\$\text{\bf{}Or use bold \rm}\text{\it{}or italic font\rm}$\\and use umlauts like äöüßÄÖÜ and accents éèêŐőŰűç};
\end{axis}
\end{tikzpicture}%
\end{document}
```

lualatex: `! Package inputenc Error: Unicode char \u8:äöü not set up for use with LaTeX.`
pdflatex compiles fine

This is the last issue I see with compiling the `testGraphical('figureVisible',true)`, followed by `make -j4` on my Linux machine on tip of `develop` with all currently open PR merged locally.

**Comment by PeterPablo** [comment]
This does not compile since my commit 764980ea, as commenting out `\usepackage[utf8]{inputenc}` makes compilation work with `lualtex`, but makes `pdflatex` fail.
Due to the new `cleanfigure` algorithm we could switch from `lualatex` to `pdflatex` in the `Makefile`s, since there are now no more issues with memory.

What should we do?

**Comment by PeterPablo** [comment]
Changing to `\usepackage[utf8]{luainputenc}` seems to make compilation work both with `pdflatex` and `lualatex`. See [ctan](http://ctan.org/pkg/luainputenc).

**Comment by egeerardyn** [comment]
The problem with `luainputenc` is that is not compatible with XeTeX (which I use for some of my documents, since that gives access to system fonts).
Maybe the best solution here is to maybe to use the [`iftex`](https://www.ctan.org/pkg/iftex?lang=en) package: this allows to check which compiler is being used and so what packages need to be loaded.

Here, I think I didn't get any problem with LuaLaTeX without `inputenc` (and I expect the same behavior on XeTeX).

**Comment by PeterPablo** [comment]
Please double check, whether compilation works for you without this patch with `luatex`. I refrained from touching the header at this point, since this would mean to yet again recalculate all hashes (with the known hassle of reliability discussions). Personally I would go with something simple that works on most environments, while allowing to compile umlauts. If you think `iftex` is the way to go, then I can do the change.

**Comment by PeterPablo** [comment]
Closing, since we now use `pdflatex` as default.
