### ISSUE TITLE
Undefined function 'm2tUpdater' for input arguments of type 'char'. 

### ISSUE THREAD

**Issue by FaizSayyid** [matlab2tikz/matlab2tikz#674]
When I try to run matlab2tikz() on matlab 2014a I get the following:

>> cleanfigure;
>> matlab2tikz()
 *** (To disable info messages, pass ['showInfo', false] to matlab2tikz.)
 *** (For all other options, type 'help matlab2tikz'.)
 *** 
 *** 
 *** This is matlab2tikz v0.6.0.
 *** 
Undefined function 'm2tUpdater' for input arguments of type 'char'.

Error in matlab2tikz (line 328)
  m2tUpdater(...

When I run it like this:

>> matlab2tikz('checkForUpdates',false)

it works

Why is this happening?

Thanks

**Comment by egeerardyn** [comment]
Probably, `m2tUpdater` is not available on your path.
Would you mind running
```matlab
p = which('matlab2tikz')
dir(fileparts(p))
dir(fullfile(fileparts(p),'private'))
```
and pasting the output here?

**Comment by egeerardyn** [comment]
I suppose this has been resolved then...
