### ISSUE TITLE
Test output for GitHub

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#675]
Since we already have two report types, i.e. for Travis (CLI) and LaTeX (PDF), I would argue that we can do with another one specifically tailored towards GitHub to allow easier communication amongst the developers. Right now it's a bit of copy-pasting into code blocks, which can probably be done somewhat better (and even the copy operation can be made automatic if we'd like).

What I propose, is to have a GitHub-flavored Markdown report. This might even replace the Travis one, depending on how readable the output is. 

What I have in mind, would have some things in there:
 - [x] a list with:
    * OS used
    * commit used
    * MATLAB/Octave version used
 - [x] a small table with the split: reliable/unreliable tests and passed/failed tests. Maybe as in Travis with some kind of obvious emoji to signal overall PASS/FAIL
 - [x] a table for the unreliable tests as in Travis (but formatted, this time)
 - [x] a table for the reliable tests as in Travis (but formatted, this time)
 - [x] factor out the output stream such that we can output to file or even clipboard
 - [x] add a report that only contains the summary and not the global breakdown.

**Comment by egeerardyn** [comment]
With #641 fresh in my memory, I think we really need a summary table with the following information:
 - tests being ordered to run (one list of the numbers, one of the names probably)
 - then a split for reliable/unreliable tests:
    - just a list of test numbers that are OK
    - just a list of test numbers that were skipped
    - the detailed information of the tests that fail (i.e. cause of failure)

The output should be in easy to copy/paste format, e.g. list of test numbers could be formatted as `x,y,z` such that pasting in MATLAB (re-running) and a shell (e.g. for uploading to gist) is convenient.

**Comment by egeerardyn** [comment]
Output streaming is factored out in all reports by now. Clipboard/string streaming has not been implemented yet. But basically, this issue can be closed.

**Comment by PeterPablo** [comment]
Since you took care of this already, I modified the milestone.

**Comment by egeerardyn** [comment]
:+1:
