### ISSUE TITLE
Stacked Bar Plots

### ISSUE THREAD

**Issue by nivek88** [matlab2tikz/matlab2tikz#676]
Hello, 

there's a problem using stacked bar plot with matlab2tikz.

If you use the Matlab example from the help site and include the .tikz in your Latex document, it doesn't look like the Matlab figure.

Is there anything to fix this problem?

Thanks.
```matlab
% Create data for childhood disease cases
measles = [38556 24472 14556 18060 19549 8122 28541 7880 3283 4135 7953 1884]';
mumps = [20178 23536 34561 37395 36072 32237 18597 9408 6005 6268 8963 13882]';
chickenPox = [37140 32169 37533 39103 33244 23269 16737 5411 3435 6052 12825 23332]';

% Create a stacked bar chart using the bar function
figure
bar(1:12, [measles mumps chickenPox], 0.5, 'stack')

% Adjust the axis limits
axis([0 13 0 100000])
set(gca, 'XTick', 1:12)

% Add title and axis labels
title('Childhood diseases by month')
xlabel('Month')
ylabel('Cases (in thousands)')

% Add a legend
legend('Measles', 'Mumps', 'Chicken pox')

matlab2tikz('example.tikz', 'noSize',true,'encoding','utf8');
```
![untitled](https://cloud.githubusercontent.com/assets/12642278/7858838/062cfd8e-053c-11e5-8b8b-7001a2873417.png)

![bildschirmfoto 2015-05-28 um 13 19 29-1](https://cloud.githubusercontent.com/assets/12642278/7858917/97c77b3e-053c-11e5-8fd5-ce8cb2fce50c.png)

**Comment by PeterPablo** [comment]
Which matlab2tikz version are you using? Please check, if the issue is present on the `develop` branch ([Download](https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip) as zip).

**Comment by nivek88** [comment]
No, it's getting even worse. 

If you don't adjust the size of the bars, you'll get this:
![bildschirmfoto 2015-05-28 um 13 36 24-1](https://cloud.githubusercontent.com/assets/12642278/7859193/ebf63ac2-053e-11e5-8896-1cfe4cf1c0f6.png)

If you adjust the size of the bars, using 

bar(1:12, [measles mumps chickenPox], 3, 'stack')

you'll get this:

![bildschirmfoto 2015-05-28 um 13 37 05-1](https://cloud.githubusercontent.com/assets/12642278/7859240/44d14902-053f-11e5-96b5-4b3593d55b9e.png)

**Comment by PeterPablo** [comment]
I can not confirm on R2104b:
![image](https://cloud.githubusercontent.com/assets/4340267/7859286/be184f90-053f-11e5-8d57-482f3ec3d325.png)

Please post the generated latex output.

**Comment by PeterPablo** [comment]
Which pgfplots and pgf versions do you have installed? Please try updating them.

**Comment by nivek88** [comment]
I'm using a Mac running Yosemite 10.10.3. I use TexMaker for compilation.
My pgf version is 2.10.
How do I update pgfplots and  pgf version?

**Comment by nivek88** [comment]
Installed The MacTeX-2014 Distribution and now my .log tells me, that I'm using pgfplots v1.10 and now pff version 3.0.0
But there still is no change.

**Comment by egeerardyn** [comment]
On Mac, the easiest way is to use the Tex Live Utility to upgrade your packages.
If your MacTeX distribution is quite old, however, it might be required to just download a newer one form the website of MacTex and do the update from the TeX Live Utility.
In MacTeX 2014, the latest version of pgfplots is 1.12.

**Comment by egeerardyn** [comment]
I have confirmed that using `pgfplots 1.10` (and R2014b) you get bad behavior (similar to what you have in your first post), but this is not the case using `pgfplots 1.12`. So upgrading your pgfplots version to 1.12 should do the trick.

So I think that solves this issue. If not: feel free to reopen this issue report :smile:

**Comment by nivek88** [comment]
It works fine now. :)
Thanks!
