### ISSUE TITLE
matlab2tikz does not produce the legend

### ISSUE THREAD

**Issue by draoul** [matlab2tikz/matlab2tikz#681]
Hello,

I am using matlab2tikz to convert a matlab figure to .tex format. However, I am experiencing some problems when I try to include a legend.

I use the following matlab code:
```javascript
hor=1:30;
x=hor.^3;
y=hor.^4/100;
figure
plot(hor,x,hor,y)
legend('Line 1','Line 2')
matlab2tikz('testlegend.tex','showInfo', false,'standalone',true); 
```

to produce the figure:
![legendmatlab](https://cloud.githubusercontent.com/assets/13016743/8305540/6191c4b0-19b0-11e5-9b8d-cac02741c1a8.jpg)

This is the .tex code produced by matlab2tikz:
```javascript
% This file was created by matlab2tikz v0.4.3.
% Copyright (c) 2008--2013, Nico Schlömer <nico.schloemer@gmail.com>
% All rights reserved.
% 
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepackage{amsmath}
\begin{document}
%
% defining custom colors
\definecolor{mycolor1}{rgb}{0,0.447,0.741}%
\definecolor{mycolor2}{rgb}{0.85,0.325,0.098}%
%
\begin{tikzpicture}

\begin{axis}[%
width=4.52083333333333in,
height=3.565625in,
scale only axis,
separate axis lines,
every outer x axis line/.append style={darkgray!60!black},
every x tick label/.append style={font=\color{darkgray!60!black}},
xmin=0,
xmax=30,
every outer y axis line/.append style={darkgray!60!black},
every y tick label/.append style={font=\color{darkgray!60!black}},
ymin=0,
ymax=30000,
legend style={draw=darkgray!60!black,fill=white,legend cell align=left}
]
\addplot [
color=mycolor1,
solid,
forget plot
]
table[row sep=crcr]{
1 1\\
2 8\\
3 27\\
4 64\\
5 125\\
6 216\\
7 343\\
8 512\\
9 729\\
10 1000\\
11 1331\\
12 1728\\
13 2197\\
14 2744\\
15 3375\\
16 4096\\
17 4913\\
18 5832\\
19 6859\\
20 8000\\
21 9261\\
22 10648\\
23 12167\\
24 13824\\
25 15625\\
26 17576\\
27 19683\\
28 21952\\
29 24389\\
30 27000\\
};
\addplot [
color=mycolor2,
solid,
forget plot
]
table[row sep=crcr]{
1 0.01\\
2 0.16\\
3 0.81\\
4 2.56\\
5 6.25\\
6 12.96\\
7 24.01\\
8 40.96\\
9 65.61\\
10 100\\
11 146.41\\
12 207.36\\
13 285.61\\
14 384.16\\
15 506.25\\
16 655.36\\
17 835.21\\
18 1049.76\\
19 1303.21\\
20 1600\\
21 1944.81\\
22 2342.56\\
23 2798.41\\
24 3317.76\\
25 3906.25\\
26 4569.76\\
27 5314.41\\
28 6146.56\\
29 7072.81\\
30 8100\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

and the corresponding figure:
![legendtex](https://cloud.githubusercontent.com/assets/13016743/8305651/8a2c95ac-19b1-11e5-872e-d23efa491167.jpg)

As one can see, the legend is missing. I googled quite a while for a solution. First, I thought that matlab2tikz maybe doesn't feature legends but then I found some threads regarding the positioning of the legends when using matlab2tikz. Does anyone know what the problem could be? Is there a best practice for including legends with matlab2tikz?

Thanks for your help!

**Comment by egeerardyn** [comment]
Thank you for the detailed error report :+1: 
This doesn't really seem related to the positioning. The fact that at each plot `forget plot` is given as an option, means that `matlab2tikz` seems to think that there should not be a legend entry.

I can't seem to reproduce this on R2014b and the R2015b pre-release with matlab2tikz 1.0 down to 0.5.0. 
Could you please give some more information about the OS you are using, what version of MATLAB and what version of matlab2tikz?

**Comment by draoul** [comment]
Thanks for your reply.

Sorry I have already closed the issue because

**Comment by okomarov** [comment]
It says matlab2tikz v0.4.3. from the header of the generated figure. 

@draoul Please, download the latest `matlab2tikz` and try again.

**Comment by draoul** [comment]
Thanks a lot for your assistance. I think have found the problem. I have noticed that I am only experiencing the problem when I am using Dynare (a frontend to matlab) before creating the plots. Apparently, Dynare relies on a modified version of matlab2tikz, which seems to cause the problem I described above.

**Comment by egeerardyn** [comment]
@draoul I think you might want to update your version of Dynare as well then (or there's something funky going on with your path).
I can't find anything `matlab2tikz`-related in their GitHub repository. So maybe there is an old version of `matlab2tikz` that is lingering on your hard drive or within the files that Dynare used to distribute (you should be able to see where it lingers if you enter `which('matlab2tikz')` when Dynare is loaded).

Anyway, I'm glad you've found the problem :+1:

**Comment by draoul** [comment]
Thanks a lot for these useful tips.
