### ISSUE TITLE
Edge of a shaded area is drawn, even when set to 'none'

### ISSUE THREAD

**Issue by draoul** [matlab2tikz/matlab2tikz#682]
Dear all,

I am experiencing a problem relating to the edge of shaded areas in my plot. In matlab, I produce a plot like this:

![shadedmatlab](https://cloud.githubusercontent.com/assets/13016743/8324724/8c517f1c-1a53-11e5-8ab5-7c5f4b8dfaf6.jpg)

This is the code I used to produce the figure:

```matlab
year=1982:2008;

Peak    = [1990.50 2001.00];
Trough  = [1991.00 2001.75];

rng(123)
x0=randn*5;
x=zeros(length(year),1);
x(1)=x0;
for ii=2:length(year)
    x(ii)=0.8+x(ii-1)+randn;
    
end
figure
plot(year,x,'k')
hold on
ylims    = get(gca,'ylim');
for i=1:size(Peak,2);
    patch([Peak(i) Trough(i) Trough(i) Peak(i)],[ylims(1) ylims(1) ylims(2) ylims(2)],[0 0 0 0],[0.7 0.7 0.7],'edgecolor','none');
end
plot(year,x,'k')
xlim([year(1) year(end)])
ylim(ylims)
title('Output','fontweight','normal')
hold off

cleanfigure;
matlab2tikz('testshaded.tex', 'standalone',true); 
```

However, when I compile the .tex file, I arrive at the following plot
![shadedtex](https://cloud.githubusercontent.com/assets/13016743/8324812/4c06d348-1a54-11e5-9e05-87b6d1f4f791.jpg)

Although, I specified the 'edgecolor' to 'none' the edge is there again. If I put 'edgecolor' to 0.7 0.7 0.7 (same as the facecolor), then the edge disappears, but unfortunately, there are gaps in the box of the figure.

How could I solve this issue?

Thanks for your help in advance!

**Comment by egeerardyn** [comment]
I can confirm this behavior and this is indeed a bug. We should fix it. I haven't looked any deeper into what is actually going on here.

**Comment by draoul** [comment]
Thanks a lot four your reply.  I thought it may be related to the patch function. Therefore, I tried to produce the plot using the area() command. However, then the generated .tex file doesn't even compile, unless I comment manually the "stack plots=y" line in the .tex file out. However, even then I experience in some cases the problem that there are gaps in the box of the figure I described above. Can you think of another workaround?

**Comment by egeerardyn** [comment]
To be honest, for the moment I don't have an idea about a work-around on the `matlab2tikz` side. From within `pgfplots`, maybe some of the `every X/.style append={...}` options might be appropriate to remove the borders, but I haven't double-checked the documentation. 
When I have some spare time, I will try to have a look at this issue, though (it probably isn't too hard to fix).

**Comment by okomarov** [comment]
@draoul I worked on `patch()` but currently don't have much time. If you post the tex with the patch I might be able to suggest a quick workaround.

**Comment by draoul** [comment]
@okomarov Below you find the .tex code to produce the figure. Thanks for your help in advance!

```
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\begin{tikzpicture}

\begin{axis}[%
width=4.521in,
height=3.566in,
at={(0.758in,0.481in)},
scale only axis,
xmin=1982,
xmax=2008,
ymin=0,
ymax=25,
axis background/.style={fill=white},
title={Output}
]
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
1982	3.82155468846217\\
1983	4.01655943463063\\
1984	3.78156762756624\\
1985	4.78297736419382\\
1986	6.2509544508795\\
1987	6.72746732296196\\
1988	8.86180320070992\\
1989	10.2832306030933\\
1990	11.0502887364881\\
1991	11.555198089902\\
1992	11.8003831026622\\
1993	13.1647572671017\\
1994	13.8310129085139\\
1995	12.9552947552216\\
1996	13.4066285937589\\
1997	15.0522093586853\\
1998	14.9412697079221\\
1999	15.2783261188798\\
2000	16.2010683003182\\
2001	17.0911060844384\\
2002	18.2110141136254\\
2003	20.07454683888\\
2004	21.7756186134666\\
2005	22.8628556960252\\
2006	24.2832103232564\\
2007	24.4379045655022\\
2008	24.8728522063716\\
};

\addplot[area legend,solid,fill=white!70!black,forget plot]
table[row sep=crcr] {%
x	y\\
1990.5	0\\
1991	0\\
1991	25\\
1990.5	25\\
}--cycle;

\addplot[area legend,solid,fill=white!70!black,forget plot]
table[row sep=crcr] {%
x	y\\
2001	0\\
2001.75	0\\
2001.75	25\\
2001	25\\
}--cycle;
\addplot [color=black,solid,forget plot]
  table[row sep=crcr]{%
1982	3.82155468846217\\
1983	4.01655943463063\\
1984	3.78156762756624\\
1985	4.78297736419382\\
1986	6.2509544508795\\
1987	6.72746732296196\\
1988	8.86180320070992\\
1989	10.2832306030933\\
1990	11.0502887364881\\
1991	11.555198089902\\
1992	11.8003831026622\\
1993	13.1647572671017\\
1994	13.8310129085139\\
1995	12.9552947552216\\
1996	13.4066285937589\\
1997	15.0522093586853\\
1998	14.9412697079221\\
1999	15.2783261188798\\
2000	16.2010683003182\\
2001	17.0911060844384\\
2002	18.2110141136254\\
2003	20.07454683888\\
2004	21.7756186134666\\
2005	22.8628556960252\\
2006	24.2832103232564\\
2007	24.4379045655022\\
2008	24.8728522063716\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

**Comment by okomarov** [comment]
The following short example reproduces the issue:
```
patch([1990.5 1991 1991 1990.5],[0 0 1 1],[0 0 0 0],[0.7 0.7 0.7],'edgecolor','none');
axis([1980, 2000, 0,1])
```

```
\documentclass[tikz]{standalone}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\begin{tikzpicture}

\begin{axis}[%
width=4.521in,
height=3.566in,
at={(0.758in,0.481in)},
scale only axis,
xmin=1980,
xmax=2000,
ymin=0,
ymax=1,
axis background/.style={fill=white},
axis x line*=bottom,
axis y line*=left
]

\addplot[area legend,solid,fill=white!70!black,forget plot,draw=none]
table[row sep=crcr] {%
x	y\\
1990.5	0\\
1991	0\\
1991	1\\
1990.5	1\\
}--cycle;
\end{axis}
\end{tikzpicture}%
\end{document}
```

For devs: I think pgfplots changed default behaviour, i.e. before an `\addplot` did not assume a `draw=black` if unspecified. Now, it requires to explicitly set `draw=none`. 

`drawPatch` attempts to set the edge color to `none`, as correctly detected from Matlab properties of the patch. Then, `setColor()` on line 1856 deals with it, and detecting a none value just drops the tikz `draw` property.

**Comment by okomarov** [comment]
Upon further inspection it is on our end. 

`\addplot` defaults to `cycle list` options when nothing is specified, and apparently the `fill=white!70!black` changes default list to wathever has the first draw color as black. 
Long-story-short, we need to fix `setColor()` to accept `none`.

**Comment by PeterPablo** [comment]
@okomarov, it would be great, if you could work on this -- time permitting. I will focus on my remaining open PRs. Thanks!
