### ISSUE TITLE
Hist3 under Matlab2013b: Problems with v.1.0.0

### ISSUE THREAD

**Issue by engineeringstatistician** [matlab2tikz/matlab2tikz#693]
Hi all,

I think there is an issue in v.1.0.0 with how hist3 plots from MATLAB are handled, at least under 2013b. The issue results in huge PDF files (30 Mb per image) being created from the .tikz (using pdflatex).

By comparing the output with my previous saved .tikz files using v.0.6.0 (and 2012b which might be an irrelevant coincidence) I found out that the relevant difference is very simple:

Previously:
```
\addplot3[%
surf,
faceted color=black,
shader=faceted,
colormap={mymap}{[1pt] rgb(0pt)=....},
mesh/rows=75]
table[row sep=crcr,header=false] {%
%
2.18965243889418	1.04390933333333	0\\
< DATA>
```

New:
```
\addplot[%
surf,
shader=faceted interp,faceted color=black,colormap={mymap}{[1pt] rgb(0pt)=....},
mesh/rows=75]
table[row sep=crcr, point meta=\thisrow{c}] {%
%
x	y	c\\
2.18965243889418	1.04390933333333	0\\
<DATA>
```

Additionally, the view={0}{90}, command is missing in the new output, probably because this is not relevant for addplot() anyay in contrast to addplot3

If I change the above differences back, the file is working fine again (size of the created PDF is less than 100k).

UPDATE: Minimum example of the MATLAB code.
```
% Generate data
n_points  = 1E3;
DATA      = repmat([2, 5],n_points,1).*randn(n_points,2);
n_grid    = 15;

colormap(jet)
hist3([DATA(:,1), DATA(:,2)], [n_grid, n_grid]);
set(get(gca,'child'),'FaceColor','interp','CDataMode','auto');
view(2)
```

And yes, you are correct, changing the 'FaceColor' property from 'interp' to 'flat' solves the issue. So basically it is not a bug but a feature in 1.0.0 which was not present in 0.6.0 :)

In case  you know better way on how to create coloured 2D histograms than the use of hist3() that would be most appreciated :)

**Comment by PeterPablo** [comment]
Could you please provide some (minimal) matlab code that can be used to provoke this behavior? Thanks!

**Comment by egeerardyn** [comment]
I think I see the problem from the TikZ output:
`shader=faceted` vs `shader=faceted interp`.

However, when I consult the pgfplots 1.12.1 manual (Section 4.6.6 / page 128 - 129), this is a known "issue":

>The choice `shader=faceted` uses a constant fill color for every mesh segment (as for flat) and the value of the key `/pgfplots/faceted color` to draw the connecting mesh elements:
> <img width="601" alt="screen shot 2015-07-12 at 12 00 58" src="https://cloud.githubusercontent.com/assets/177360/8637354/b6b86f84-288d-11e5-84e3-ec841ad78530.png">
>The last choice is `shader=faceted interp`. As the name suggests, it is a mixture of `interp` and `faceted` in the sense that each element is shaded using linear triangle interpolation (see also the patch- plots library for bilinear interpolation) in the same way as for `interp`, but additionally, the edges are colored in faceted color:
> <img width="603" alt="screen shot 2015-07-12 at 12 01 07" src="https://cloud.githubusercontent.com/assets/177360/8637356/bc05b17c-288d-11e5-8a13-16c71d7377a6.png">
>**In principle, there is nothing wrong with the idea as such, and it looks quite good – but it enlarges the resulting pdf document considerably and might take a long time to render**. It works as follows: for every mesh element (either triangle for patch plots or rectangle for lattice plots), it creates a low level shading. It then fills the single mesh element with that shading, and strokes the edges with faceted color. The declaration of that many low level shadings is rather inefficient in terms of pdf objects (large output files) and might render slowly. For orthogonal plots (like `view={0}{90}`), the effect of `faceted interp` can be gained with less cost if one uses two separate `\addplot` commands: one with surf and one with mesh. Handle this choice with care.

I think that using either `faceted` or `interp` might not be the right (generic) solution, since they look quite a bit different. As far as I can see from our source code, we use `faceted interp` when your surface plot  has its `FaceColor = 'interp'` and `EdgeColor = 'flat'`, which we rightfully translate to `faceted interp`. 

If you prefer the old output, I think that setting its `FaceColor = 'flat'` and `EdgeColor = 'interp'` would accomplish that:
```matlab
h = surf(...)
set(h, 'FaceColor', 'flat', 'EdgeColor', 'interp');
matlab2tikz(...)
```
But since you don't have an MWE, I can't quickly test that on my end.

**Comment by engineeringstatistician** [comment]
I updated the first post with an example. You are correct, changing the option to "flat" solves the issue. In my opinion it would be helpful to have a warning message displayed maybe. It was just by chance that  I or you, respectively, stumbled across the reason for this issue which could have been quite a bugger when writing a thesis with many such graphs that become unexplicably large.

**Comment by egeerardyn** [comment]
I agree that we should try to warn the user about this. And in the case of `hist3`, I think those settings often make little sense (unless you indeed specify `view(2)` which makes the remark in the manual very relevant: probably it's better to make a mesh and a surf). The graphical output from that view also seems identical with `FaceColor = 'flat'`.

We can certainly put a warning when we specify that option and I think it would certainly be possible to fall back to flat face colors when the view is orthogonal.

**Comment by egeerardyn** [comment]
Since #699 we now warn for this situation and refer back to this this issue report.
Unlike what I said before, I don't think we should apply any workarounds automatically.
