### ISSUE TITLE
Legend of bode plot

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#700]
As indicated by @tomlankhorst in #667:

> This seems not to work in my case, legend entries still missing:
>```matlab
> bode(tf([1],[1 1]));
> legend('G0');
> cleanfigure
> matlab2tikz('legendbode.tex', 'standalone', true)
> !pdflatex legendbode.tex
>```
> Results in PDF without the text 'G0' in the legend.

Personally, I can confirm the behavior on R2014b: bode plot legends are not OK.

**Comment by tomlankhorst** [comment]
Traced down to missing \addlegendentry{} argument in the generated tex-file.

**Comment by PeterPablo** [comment]
@tomlankhorst, you are very welcome to try to fix this issue yourself and commit a pull request against the `develop` branch. We will certainly assist you in case of questions (e.g. concerning the use of `git`). Are you interested?

**Comment by tomlankhorst** [comment]
Hi Peter, I'll give it a try.

**Comment by tomlankhorst** [comment]
https://github.com/matlab2tikz/matlab2tikz/pull/702

**Comment by egeerardyn** [comment]
Closed by #702.

**Comment by miscco** [comment]
BTW, is it just my hacky version or does cleanfigure tamper with the bode plot?

**Comment by egeerardyn** [comment]
@miscco Cleanfigure only seems to remove some points here, nothing really special. What are you experiencing?

**Comment by miscco** [comment]
For me it changes the graph at least in matlab. It can be, that it is only MATLAB2015a or it has no visual effect in tikz however.
Before cleanfigure:

![bode_before](https://cloud.githubusercontent.com/assets/3017120/9716251/54ff3644-5568-11e5-8c46-e7ab04e7d9a9.jpg)

After cleanfigure:
![bode_after](https://cloud.githubusercontent.com/assets/3017120/9716252/54ff598a-5568-11e5-81ed-c5c15f452fbf.jpg)

**Comment by okomarov** [comment]
@miscco @egeerardyn  Not to be a bummer, but this is not related to legends. Please, consider issuing a new ticket.
