### ISSUE TITLE
drawAnnotations fails: "Invalid handles passed to findall."

### ISSUE THREAD

**Issue by dachziegel** [matlab2tikz/matlab2tikz#728]
I have a MATLAB fig file which I opened and then called `matlab2tikz` (latest version from development branch)

It failed with:
<pre>
Error using findall (line 24)
Invalid handles passed to findall.

Error in matlab2tikz>drawAnnotations (line 2538)
        annotHandles = findall(allchild(annotPanes),'Visible','on');

Error in matlab2tikz>saveToFile (line 454)
    m2t = drawAnnotations(m2t);

Error in matlab2tikz (line 347)
saveToFile(m2t, fid, fileWasOpen);
</pre>

This happened in R2015a on Linux.
The fig-file which caused the bug is available at https://gist.github.com/dachziegel/df4f74df9fca63556119#file-test-fig

**Comment by egeerardyn** [comment]
Fixed by #730.
