### ISSUE TITLE
Jenkins is unreliable

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#769]
This issue report is a notice of two things.
As @okomarov mentioned in #760, sometimes (but not every time as evidenced by #768) an old commit gets built in PRs when new commits are pushed.

This e.g. happened in [build 148](http://pixiebox.synology.me:8090/job/matlab2tikz/148) (which on first inspection looks identical to 149), but once you inspect the [console output of one of the matrix components](http://pixiebox.synology.me:8090/job/matlab2tikz/Runner=octave%20--eval/148/console), you see that the old commit is checked out and built.

What I noticed between 148 and 149 is that the environment variables do change (i.e. `GIT_COMMIT`).

Current workaround is to ask the bot explicitly to test the PR.

A few ideas of mine:
 - maybe this is a weird race condition? I have already increased the dead time to decrease the possibility.
 - we could fetch & check out again in the Jenkins script
 - we could break up the matrix into loose builds (we'd have to test this again and this duplicates the complicated configuration, so this is very last resort)

Feel free to experiment with the Jenkins server if you're brave.

**Comment by egeerardyn** [comment]
I've restored the `commit` identifier back to `${sha1}` (this is a symbolic name for the last commit in the PR merged back into the branch against which the pull is requested) instead of `${ghprbActualCommit}` (this is the last commit in the PR).

Also, in the presumption that this is a race condition (where the sub-builds are somehow delayed a bit and cannot fetch the last commit), I have increased the dead time before a build starts to 10 seconds.

If that doesn't fix everything, I think we can add some checks to the build script, e.g.
 1. [check if `${ghprbActualCommit}` (last commit in PR as hash) is an ancestor of `${GIT_COMMIT}` (actual checkout on the server)](http://stackoverflow.com/questions/3005392/how-can-i-tell-if-one-commit-is-a-descendant-of-another-commit)
 2. if not, then just exit the build script with an error code + message (i.e. make the build fail)

That would prevent false positives, at the cost of introducing false negatives. And since one needs to inspect build failures, it could be obvious that the test needs to be restarted. We can even add an entry to the cause management to make this condition obvious as well. Just clicking on "Rebuild"  (or saying the build phrase on Github) can then fix the situation.

**Comment by okomarov** [comment]
Haha, but I changed from sha1...forgot to tell

Sent from my iPhone

On 12 Sep 2015, at 11:33, "Egon Geerardyn" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've restored the commit identifier back to ${sha1} (this is a symbolic name for the last commit in the PR merged back into the branch against which the pull is requested) instead of ${ghprbActualCommit} (this is the last commit in the PR).

Also, in the presumption that this is a race condition (where the sub-builds are somehow delayed a bit and cannot fetch the last commit), I have increased the dead time before a build starts to 10 seconds.

If that doesn't fix everything, I think we can add some checks to the build script, e.g.

  1.  check if ${ghprbActualCommit} (last commit in PR as hash) is an ancestor of ${GIT_COMMIT} (actual checkout on the server)<http://stackoverflow.com/questions/3005392/how-can-i-tell-if-one-commit-is-a-descendant-of-another-commit>
  2.  if not, then just exit the build script with an error code + message (i.e. make the build fail)

That would prevent false positives, at the cost of introducing false negatives. And since one needs to inspect build failures, it could be obvious that the test needs to be restarted. We can even add an entry to the cause management to make this condition obvious as well. Just clicking on "Rebuild" (or saying the build phrase on Github) can then fix the situation.

**Comment by egeerardyn** [comment]
@okomarov I guessed so :smile: Don't worry, it's just that I think that makes little sense to test the commit directly:
 * it's a different result from Travis
 * if one still needs to resolve merge conflicts, testing will have to be repeated anyway (so testing the merged commit is the right thing to do (though not obvious at first))

**Comment by okomarov** [comment]
👍

Sent from my iPhone

On 12 Sep 2015, at 11:38, "Egon Geerardyn" <notifications@github.com<mailto:notifications@github.com>> wrote:


@okomarov<https://github.com/okomarov> I guessed so [:smile:]  Don't worry, it's just that I think that makes little sense to test the commit directly:

  *   it's a different result from Travis
  *   if one still needs to resolve merge conflicts, testing will have to be repeated anyway (so testing the merged commit is the right thing to do (though not obvious at first))

**Comment by okomarov** [comment]
Now it gives (http://pixiebox.synology.me:8090/job/matlab2tikz/162/):
ERROR: Error fetching remote repo 'origin'

**Comment by egeerardyn** [comment]
@okomarov: I have the impression my internet connection is a bit unstable at the moment (I suspect DNS troubles), causing the builds to fail. I will inspect this further tomorrow night.

**Comment by okomarov** [comment]
@egeerardyn I am still unsure that `${ghprbActualCommit}` means it does NOT merge back into develop.

**Comment by egeerardyn** [comment]
What makes you think that? I'm quite positive it means exactly that because:
 - if you look at `${ghprbActualCommit}` from e.g. [Build 157](http://pixiebox.synology.me:8090/job/matlab2tikz/157/compare_environment/), you will see that it is df7560c, which is one of the commits in the related PR (#760). I.e. there is no merge commit with `develop` in there.
 - According to the [GitHub help](https://help.github.com/articles/checking-out-pull-requests-locally/), one could fetch e.g. `pr/760/head` to obtain the same commit (well, at least at that point in time).
 - E.g. [this website](http://blog.jetbrains.com/teamcity/2013/02/automatically-building-pull-requests-from-github-with-teamcity/) under the "Configuring TeamCity" section tells the same as I do, `pr/N/merge` is `pr/N/head` merged back into the branch against which the PR is filed (well, they say `master`, but in most other repositories, that's the same thing).

Also, you should be able to backtrack the different environment variables in Jenkins using `Compare Environments` (see one of the links above), that usually helps me a bit to see what's going on.

**Comment by egeerardyn** [comment]
Slightly related: I had a build that was marked "failed" because `libncurses` has been updated from ABI 5 to ABI 6 (`libncurses.so.6`) on Arch Linux, while MATLAB is compiled against the `.so.5` version. Anyhow, everything should be fine now.

Unfortunately, I can't succeed in setting a proper fail cause pattern for those patterns.

**Comment by egeerardyn** [comment]
Closing, as I have not seen this behavior again over the last few months (admittedly, I have not been that active those months, but I don't think keeping this open does any good).
