### ISSUE TITLE
simplify 3D plots

### ISSUE THREAD

**Issue by miscco** [matlab2tikz/matlab2tikz#777]
Hi,

I have currently a problem with a 3D plot with a large amount of data points. Sadly most of those are clustered at some position, whereas at some parts of the plot there are only few points. Therefore a simple decimate or downsample doesn't cut it. 

Long story short i thought about whether we could use the simplifyLine function also for 3D plot. The problem with that approach is obvious but theoretically solvable.

My idea is to take the view that we get and utilize it to projekt the 3D coordinates onto the 2D view plane. Then we would run our 2D simplifyLine and get the mask for those points we would ommit (note that we do not need the back transformation as we simple omit points)

So I thought about something along those lines (see https://en.wikipedia.org/wiki/Camera_matrix)

```matlab
% 3D data in 4D view
data = [xData(:), yData(:), zData(:), ones(size(xData(:)))];

% Get the current view
C = view;

% remove the unneeded 4th column
C = C(1:3,:);

% Project the data
data_transformed = (view*data')';

% scale the data
data_transformed =[data_transformed(:,1)./data_transformed(:,3),...
                                data_transformed(:,2)./data_transformed(:,3)];

mask = opheimSimplify(data_transformed(:,1), data_transformed(:,2) , tol);
```

However, if I then plot(data_transformed(:,1), data_transformed(:,2)) I get something slightly different then what i would expect. So i am unsure where i am doing things wrong

The 3D figure
![3d_plot](https://cloud.githubusercontent.com/assets/3017120/10022692/6c51b83e-614e-11e5-9a83-770c75cba035.png)

The corresponding 2D projection
![2d_projection_plot](https://cloud.githubusercontent.com/assets/3017120/10022699/773cad62-614e-11e5-9364-47a2e97a21d3.png)

**Comment by egeerardyn** [comment]
@missco I'm by no means experienced with 3D stuff, but I have 2 remarks:

1. the 4th coordinate in those quaternions does matter (it allows for translations in the same manner as a rotation)
2. I don't see your logic in dividing the X and Y coordinates by the Z coordinates in the transformed data. Maybe that is the problem?

Also, for testing you might want to overlay (or subplot) the 2 axes (the original 3D one and a 2D one with your calculations) to visually compare your results more easily.

In any case: thank you for looking into this. The idea seems nice, so let's hope we can implement it in a reliable way as well :+1:

**Comment by okomarov** [comment]
It is a good idea! Unfortunately, the `c = view()` is undocumented syntax and I suspect from your plots that the transformation matrix it gives back is a projection on the plane with `z = 1`.

Actually we should use `vievmtx()` to query the projection onto the camera plane.

**Comment by okomarov** [comment]
This example works:

```matlab
h = ezplot3('cos(t)', 'sin(t)', 'sin(5*t)', [-pi pi]);

data = get(h,{'XData','YData','Zdata'});
data = [cat(1,data{:})', ones(numel(data{1}),1)];

% Projection matrix on screen
[az,el] = view();
A = viewmtx(az,el);

data_transformed = A*data';
plot(data_transformed(1,:), data_transformed(2,:))  
```

adapted from an example in `viewmtx()`.

**Comment by miscco** [comment]
Sweet, that is really nice. 

Sometimes thinks just seem to work. Never even really checked, that view() is actually not supported ;)

I will submit a PR tomorrow. However, it will definitely depend on #761 otherwise there might be data blocks, that are full of NaN in one dimension.

**Comment by okomarov** [comment]
Please do not subordinate to #761, there is no need and also that PR is already waiting to be merged after another one.

This PR is independent of the problem outlined in #761 since it does not solve nor **worsens** the current develop branch with respect to inf in the data.

It's gonna be quicker to test and merge it.

Sent from my iPhone

On 22 Sep 2015, at 20:17, "Michael Schellenberger Costa" <notifications@github.com<mailto:notifications@github.com>> wrote:


Sweet, that is really nice.

Sometimes thinks just seem to work. Never even really checked, that view() is actually not supported ;)

I will submit a PR tomorrow. However, it will definitely depend on #761<https://github.com/matlab2tikz/matlab2tikz/pull/761> otherwise there might be data blocks, that are full of NaN in one dimension.

**Comment by miscco** [comment]
So as this seems to be fixed by #790 i think we can close this

**Comment by okomarov** [comment]
It's not merged yet.

**Comment by miscco** [comment]
As #790 is merged, this is not longer an issue :)
