### ISSUE TITLE
Layering of barplots broken

### ISSUE THREAD

**Issue by miscco** [matlab2tikz/matlab2tikz#800]
So similarly on my MATLAB2015b, the layering of barplots is brocken. This becomes visible in the following ACID tests:
ACID(34)
ACID(94)
ACID(97-99) -> These ones actually get the figure right and the reference is wrong

The figure after cleanfigure is still fine.What is missing is the following line in the axis definition:
```
stack plots=y,
```

![test34-converted](https://cloud.githubusercontent.com/assets/3017120/10691062/7f7b4704-7986-11e5-9165-814225c087d5.jpg)

Can somebody test for earlier MATLAB releases?

**Comment by miscco** [comment]
What i found is, that in test 94 the added "stack plots=y" does the trick for the bar plots, but it messes with the line plot
![test94-converted](https://cloud.githubusercontent.com/assets/3017120/10690989/e39a2b66-7985-11e5-87d4-720e15c60577.jpg)

**Comment by PeterPablo** [comment]
Maybe [this](https://github.com/matlab2tikz/matlab2tikz/blob/develop/src/matlab2tikz.m#L3815) is the culprit. It was touched in https://github.com/matlab2tikz/matlab2tikz/commit/bb049e20c83c554f336b1344a22f9ef928a29270. Sorry, I can't help much currently with development.

**Comment by miscco** [comment]
As far as i can say it is not. I tried manually changing the order of the bar plots and it does not change anything in the figure

**Comment by PeterPablo** [comment]
You might want to try the 1.0 release, to see if it is a regression that
was introduced recently. Unfortunately I also only can run 2015b.

**Comment by miscco** [comment]
Tested, the same bug is apparent in master

**Comment by egeerardyn** [comment]
@miscco Don't those examples use `xbar stacked` or `ybar stacked` ? That is almost equivalent to `xbar, stack plots=x` (or `y`) with some added advantages according to the `pgfplots` manual, e.g. 

<img width="784" alt="screen shot 2015-10-23 at 16 11 51" src="https://cloud.githubusercontent.com/assets/177360/10694852/cc9ec2c6-79a0-11e5-9376-f87d1a8c699c.png">

If you want to track down the changes further: I have made major changes to handling of bar plots between m2t 0.5 and 1.0 (I think before almost everything was translated into patches instead of bars). But the only thing I can really think of, is that you might be using an old version of pgfplots.

**Comment by okomarov** [comment]
@miscco I cannot reproduce your problem in R2015b:

![capture](https://cloud.githubusercontent.com/assets/3731173/10739427/33db74fa-7c14-11e5-971d-dd2187255701.PNG)


```latex
% This file was created by matlab2tikz.
%
%The latest updates can be retrieved from
%  http://www.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz
%where you can also make suggestions and rate matlab2tikz.
%
\documentclass[tikz]{standalone}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{pgfplots}
\usepackage{grffile}
\pgfplotsset{compat=newest}
\usetikzlibrary{plotmarks}
\usetikzlibrary{arrows.meta}
\usepgfplotslibrary{patchplots}
\usepackage{amsmath}

\begin{document}
\definecolor{mycolor1}{rgb}{1.00000,0.00000,1.00000}%
\definecolor{mycolor2}{rgb}{0.21783,0.72504,0.61926}%
\definecolor{mycolor3}{rgb}{0.97630,0.98310,0.05380}%
\definecolor{mycolor4}{rgb}{0.20810,0.16630,0.52920}%
\definecolor{mycolor5}{rgb}{0.00000,1.00000,1.00000}%
%
\begin{tikzpicture}

\begin{axis}[%
width=1.952in,
height=1.493in,
at={(0.758in,2.554in)},
scale only axis,
xmin=-6.25,
xmax=6.25,
ymin=0,
ymax=100,
axis background/.style={fill=white}
]
\addplot[ybar,bar width=0.333,bar shift=-0.222,draw=none,fill=mycolor1,area legend] plot table[row sep=crcr] {%
-5	42\\
-4	76\\
-3	96\\
-2	99\\
-1	83\\
0	51\\
1	11\\
2	32\\
3	69\\
4	93\\
5	100\\
};
\addplot[ybar,bar width=0.333,draw=black,fill=mycolor2,area legend] plot table[row sep=crcr] {%
-5	100\\
-4	1\\
-3	100\\
-2	2\\
-1	100\\
0	3\\
1	100\\
2	4\\
3	100\\
4	4\\
5	100\\
};
\addplot[ybar,bar width=0.333,bar shift=0.222,draw=black,fill=mycolor3,area legend] plot table[row sep=crcr] {%
-5	66\\
-4	99\\
-3	84\\
-2	27\\
-1	43\\
0	92\\
1	95\\
2	52\\
3	17\\
4	77\\
5	100\\
};
\end{axis}

\begin{axis}[%
width=1.952in,
height=1.493in,
at={(3.327in,2.554in)},
scale only axis,
xmin=0,
xmax=100,
ymin=-10,
ymax=10,
axis background/.style={fill=white}
]
\addplot[xbar,bar width=0.289,bar shift=-0.222,draw=black,fill=mycolor4,area legend] plot table[row sep=crcr] {%
42	-5\\
76	-4\\
96	-3\\
99	-2\\
83	-1\\
51	0\\
11	1\\
32	2\\
69	3\\
93	4\\
100	5\\
};
\addplot[xbar,bar width=0.289,draw=black,fill=mycolor2,area legend] plot table[row sep=crcr] {%
100	-5\\
1	-4\\
100	-3\\
2	-2\\
100	-1\\
3	0\\
100	1\\
4	2\\
100	3\\
4	4\\
100	5\\
};
\addplot[xbar,bar width=0.289,bar shift=0.222,draw=black,fill=mycolor3,area legend] plot table[row sep=crcr] {%
66	-5\\
99	-4\\
84	-3\\
27	-2\\
43	-1\\
92	0\\
95	1\\
52	2\\
17	3\\
77	4\\
100	5\\
};
\end{axis}

\begin{axis}[%
width=1.952in,
height=1.493in,
at={(0.758in,0.481in)},
scale only axis,
bar width=0.8,
xmin=0,
xmax=6,
xtick={1, 2, 3, 4, 5},
ymin=0,
ymax=20,
axis background/.style={fill=white}
]
\addplot[ybar stacked,draw=black,fill=mycolor4,area legend] plot table[row sep=crcr] {%
1	1\\
2	1\\
3	1\\
4	4\\
5	4\\
};
\addplot[ybar stacked,draw=black,fill=mycolor2,area legend] plot table[row sep=crcr] {%
1	1\\
2	2\\
3	1\\
4	5\\
5	5\\
};
\addplot[ybar stacked,draw=black,fill=mycolor3,area legend] plot table[row sep=crcr] {%
1	1\\
2	2\\
3	1\\
4	7\\
5	8\\
};
\end{axis}

\begin{axis}[%
width=1.952in,
height=1.493in,
at={(3.327in,0.481in)},
scale only axis,
bar width=0.75,
xmin=0,
xmax=20,
ymin=0,
ymax=6,
ytick={1, 2, 3, 4, 5},
axis background/.style={fill=white}
]
\addplot[xbar stacked,draw=none,fill=mycolor5,area legend] plot table[row sep=crcr] {%
1	1\\
1	2\\
1	3\\
4	4\\
4	5\\
};
\addplot[xbar stacked,draw=black,fill=mycolor2,area legend] plot table[row sep=crcr] {%
1	1\\
2	2\\
1	3\\
5	4\\
5	5\\
};
\addplot[xbar stacked,draw=black,fill=mycolor3,area legend] plot table[row sep=crcr] {%
1	1\\
2	2\\
1	3\\
7	4\\
8	5\\
};
\end{axis}
\end{tikzpicture}%
\end{document}
```

**Comment by miscco** [comment]
Hm when i have some time i am going to check with my pgf version

**Comment by egeerardyn** [comment]
@miscco If you run the tests with `testGraphical`, there is a table in `acid.tex` that shows the `pgfplots` version used.

**Comment by miscco** [comment]
Ah so i have 1.9, i will update next week maybe

**Comment by miscco** [comment]
So i updated my installation of pgfplots and now everything plots cleanly.
