### ISSUE TITLE
replace 'plot table' with 'table'

### ISSUE THREAD

**Issue by okomarov** [matlab2tikz/matlab2tikz#801]
All around is used:

    str = sprintf('%s\\addplot[%s] plot table[%s] {%s};\n', ...

while it should be according to the pgfplots manual 

    str = sprintf('%s\\addplot[%s] table[%s] {%s};\n', ...

To be consistent with the manual, replace all instances of `plot table` with simply `table`.

**Comment by egeerardyn** [comment]
I will tackle this, once all current PRs are dealt with.
