### ISSUE TITLE
remove `double(gca)` conversions

### ISSUE THREAD

**Issue by okomarov** [matlab2tikz/matlab2tikz#802]
As pointed out in https://github.com/matlab2tikz/matlab2tikz/issues/383 some properties that can be used to implement additional features are dropped during  `double(gca)` conversions of the axes handles. 

These properties are hidden but often stable, and thus would allow for additiona of features/bug fixes that otherwise would be very hacky to implement. 

This should matter to HG2 only.

**Comment by egeerardyn** [comment]
I searched our codebase for such calls (regular expression `[^a-zA-Z0-9]double\(`) and this is what I found:

**Searching 14 files for `[^a-zA-Z0-9]double\(` (regex, case sensitive)**

*/Users/egon/Dropbox/matlab/matlab2tikz/src/figure2dot.m:*
```matlab
   83                  % don't do anything
   84              end
   85:             label = addProperty(label, 'Handle', sprintf('%g', double(h)));
   86              label = addHGProperty(label, h, 'Title', '');
   87              label = addHGProperty(label, h, 'String', '');
```

#/Users/egon/Dropbox/matlab/matlab2tikz/src/matlab2tikz.m:*
```matlab
 1181      legendEntries = m2t.axesContainers{end}.LegendEntries;
 1182      if isnumeric(h)
 1183:         legendEntries = double(legendEntries);
 1184      end
 1185  
 ....
 1194      plotyyReferences = m2t.axesContainers{end}.PlotyyReferences;
 1195      if isnumeric(h)
 1196:         plotyyReferences = double(plotyyReferences);
 1197      end
 1198  
```
3 matches across 2 files

# My analysis
In `figure2dot`, it's not a problem: it's just a way to track down an identifier (and that is a dev-only tool).

In m2t, the actual fragment where both occur is:
```matlab
function [m2t, bool] = hasLegendEntry(m2t, h)
    % Check if the handle has a legend entry and track its legend status in m2t
    legendEntries = m2t.axesContainers{end}.LegendEntries;
    if isnumeric(h)
        legendEntries = double(legendEntries);
    end

    % Should not have a legend reference
    bool = any(ismember(h, legendEntries)) && ...
           ~hasPlotyyReference(m2t,h);
    m2t.currentHandleHasLegend = bool;
end
% ==============================================================================
function bool = hasPlotyyReference(m2t,h)
    % Check if the handle has a legend reference
    plotyyReferences = m2t.axesContainers{end}.PlotyyReferences;
    if isnumeric(h)
        plotyyReferences = double(plotyyReferences);
    end

    bool = any(ismember(h, plotyyReferences));
end
```

So there, it is only used to check membership in a set of objects and those doubles don't leave the function.

# Conclusion
We do perform such typecasts, but the casted values are not leaving the function scopes where they are actually needed.
Hence, we can close this issue.
