### ISSUE TITLE
Suggestion: Cleaning up stairs plots

### ISSUE THREAD

**Issue by bobpepin** [matlab2tikz/matlab2tikz#863]
Hi,
I found the following useful to clean up a stairs plot where the function is constant over some interval. It replaces for example `[(x_1, y_1), (x_2, y_1), ... (x_k, y_1), (x_{k+1} y_2)]` by `[(x_1, y_1), (x_{k+1} y_2)]`.

```matlab
% h is a handle to a 'stairs' object
I = [true (diff(h.YData) > 0)];
set(h, 'XData', h.XData(I), 'YData', h.YData(I));
```

Regards,
Bob

**Comment by egeerardyn** [comment]
Thank you for this suggestion! We will do our best to integrate it into `cleanfigure`

**Comment by miscco** [comment]
As far as I know, the lineSimplification in the development branch should do exactly that. Have you tried it?

**Comment by okomarov** [comment]
@miscco stair plots are not currently simplified (line 130 of cleanfigure)

**Comment by miscco** [comment]
Is there any reason for that?`Just add ing 
```
% Simplify the lines by removing superflous points
simplifyLine(meta, h, cmdOpts.targetResolution);
```
should do the trick, or are there weird handle types involved?

**Comment by okomarov** [comment]
Probably HG1 vs HG2 compatibility (type detection and potential changes in the graphical object) + Octave differences. Also, this feature has been fairly low-prioprity, since stairs plots need a very limited amount of data (unless @bobpepin has a specific use case he wants to share), hence very unlikely to generate out-of-memory in latex.

**Comment by egeerardyn** [comment]
I agree with @okomarov that it is quite low-priority (IMHO since few people use `stair` plots), but I also think this is a quick fix (there are some things we could tweak, but not a lot: `==` instead of `<` and maybe also check the other direction). I especially like that it's just a really simple algorithm and it is lossless compression (unlike `simplifyLine` which can be lossy). So in my book, this is a no-brainer: we should add it.

Since `stairs` and `plot` use a different strategy to interpolate between each pair of points, `simplifyLine` is not applicable.
In the example below, `simplifyLine` should remove all points except the first and the last. 
For `line` that is desired behavior. For `stairs` it is not.

```matlab
x = 1:10
y = 2*x
figure, hold all
stairs(x,y)
plot(x,y)
legend('stairs','line')
```
<img width="471" alt="screen shot 2016-02-15 at 18 19 52" src="https://cloud.githubusercontent.com/assets/177360/13055628/c31a7806-d410-11e5-8f0a-3a2ad190cc4f.png">

**Comment by bobpepin** [comment]
For what it's worth, my use case is a quick and dirty way for approximating a function z(t) that is equal to a_n on intervals of length a_n:
a_n = linspace(10, 20, 40);
z_k = repelem(a_n, round(a_n*1000));

This generates latex out of memory using only cleanfigure, not surprisingly since
$ du -h figures/zk*.tikz
 20M	figures/zk.tikz
8.0K	figures/zk_clean.tikz
(the second is the diff-simplified one of course)

Interestingly, plotting performance in matlab is about the same for both cases, however there are big differences when exporting to PDF for example.

And of course there has to be a ~= instead of the > in the original code.

**Comment by egeerardyn** [comment]
@bobpepin 
That looks like quite a dirty approach, since it introduces a whole lot of duplicates that you don't actually need. I suspect you can make that code a whole lot better by using `cumsum` (e.g. I would try to run `cumsum(a_n)` which should give you the X-values of the stairs plot or something that is already quite close.

Anyway, I think your simplification algorithm remains valuable for inclusion in `cleanfigure`: it's simple and does a reasonable job. I see no reason not to include it (it will just take a bit of time, since this is not our top priority right now).

**Comment by bobpepin** [comment]
Not only dirty, but also quick;) especially since it is being fed into some C code, and modifying that to work with time intervals would seriously hurt the quickness of the approach (mostly in terms of developer time of course). Sorry for the off-topic, and thanks for developing matlab2tikz.
Cheers,
Bob

**Comment by egeerardyn** [comment]
Don't worry :smile: I perfectly understand you are hesitant to change embedded code that works.

**Comment by miscco** [comment]
I would go with something like this, however I am unsure about 3D data, is that possible with stairs?
```matlab
function simplifyStairs(meta, handle)
   % Some data might not lead to a new step in the stair, e.g.
   % [(x_1, y_1), (x_2, y_1), ... (x_k, y_1), (x_{k+1} y_2)] by [(x_1, y_1), (x_{k+1} y_2)]

    % Extract the data
    xData = get(h, 'XData');
    yData = get(h, 'YData');

    % Dont do anything if the data is empty
    if isempty(XData) || isempty(YData)
        return;
    end

    % Check which point do lead to a new step
    xStep = [true, (diff(XData) ~= 0)];
    yStep = [true, (diff(YData) ~= 0)];

    % Plot only points, that generate a new step
    id_remove = ~xStep && ~yStep;

    % Remove the superfluous data
    removeData(meta, handle, id_remove);

    return;
```

**Comment by okomarov** [comment]
Logic looks good :+1:, we just need to check visually which end of the stair matters, the left one or right one. I recall some funky behaviour.

Minor comments, the `return;` at the end is not necessary and the `;` after return also not necessary.

**Comment by bobpepin** [comment]
pruning the ydata in this way of course only works if xdata is increasing and vice versa. So you might want to check min(diff(XData)) >= 0 before cleaning YData. If Matlab allows non-increasing XData for stairs, that is.

**Comment by egeerardyn** [comment]
@bobpepin good point about the monotonicity

**Comment by miscco** [comment]
@bobpepin I cant follow you here. The condition used int my example code is ~=0 so it is independent of the monotonicity

**Comment by miscco** [comment]
Creating the PR i found, that the &(and)  for finding missing steps is obviously wrong, it should be an | (or) as either one fo them would results in a continuous line.

**Comment by miscco** [comment]
@okomarov I believe, you are right. We have to set the last datapoint to true to avoid shortening the plot. The first is already explicitly set.

**Comment by bobpepin** [comment]
Regarding monotonicity, consider the following sequence of (x, y) coordinates:
(0, 1), (0, -1), (0, 2)
Keeping only the first and last will remove the line segment from -1 to 0. To be precise, for each interval of constant x, we would have to draw the line from min(y) to max(y). When the x coordinates are monotone, this is the first and the last point, hence the algorithm works.

**Comment by okomarov** [comment]
@bobpepin the coordinates you are giving are not monotone. The diff is tested on both x AND y.

**Comment by bobpepin** [comment]
@okomarov do we agree that (0, -1), (0, 1), (0, 2) should be replaced by (0, -1), (0, 2) ? And that ideally, (0, 1), (0, -1), (0, 2) should be replaced by (0, -1), (0, 2) as well, but that the current algorithm would replace it by (0, 1), (0, 2) which is wrong (taking into account @miscco's latest comment regarding "|"  instead of "&")?
In this case, the solution would be either not to simplify the second example, or use a more sophisticated algorithm, for example something along the lines of: 
remove diff(xData == 0) & diff(yData >= 0)
remove diff(xData == 0) & diff(yData <= 0) 
until convergence.
Or you could somehow sort the datapoints before to ensure monotonicity.
Although this somehow destroys the simplicity of the original 2-line algorithm, and I'm not sure how common non-monotone stair plots are.

**Comment by miscco** [comment]
@bobpepin Yeah, I see the problem, i think here the signum of the diff would be usefull. However, i am currently full with work so i will check maybe late this WE.

**Comment by okomarov** [comment]
For a well-behaved stairs plot (base case), the condition should then be:

```
x = [0, 0, 0]
y = [1, -1, 2]
~([true, (diff(x) ~= 0)] | [true, (diff(y) ~= 0)])
ans =
     0     0     0
```
i.e. no simplification. And we can merge the PR and add a smarter algorithm in a second step (sortrows the matrix of coordinates, apply diff as above, and pass the sorted positions to remove).

**Comment by egeerardyn** [comment]
The only thing I don't like about that last snippet is the double negation. It's probably better to introduce temp variables then.

**Comment by miscco** [comment]
@egeerardyn  i could change the definition to [false, diff()==0] ?

**Comment by egeerardyn** [comment]
@miscco Indeed, that would be better, something like
```matlab
([false, diff(x)==0] & [false, diff(y)==0])
```
or
```matlab
xIsConstant = [false, diff(x) == 0];
yIsConstant = [false, diff(y) == 0];
idxToRemove = xIsConstant & yIsConstant;
```

I think that will, however, be very restrictive in what it removes, i.e. only duplicate points as I see it. 

The alternative, is that we could check if X is monotone, if so, do the simple algorithms from the beginning. I think that hits a pragmatic sweet spot with respect to the typical use case of stair plots and complexity of the code.

**Comment by miscco** [comment]
We could use the sign function here:
```
Y = sign(x) returns an array Y the same size as x, where each element of Y is:

    1 if the corresponding element of x is greater than 0.

    0 if the corresponding element of x equals 0.

    -1 if the corresponding element of x is less than 0.
```
If we apply that on the diff() then it should give us a correct result

**Comment by okomarov** [comment]
I am not grasping how the `sign()` would solve the issue, can you provide and example?

**Comment by egeerardyn** [comment]
If `sign(diff(x))` has a constant sign (so all elements either in `[0 -1]` or `[0 1]`, but not `[-1 0 1]`) then the function is monotonous.

**Comment by miscco** [comment]
So as #865 has been merged i believe we can close this
