### ISSUE TITLE
Contour plots: line width + color is off

### ISSUE THREAD

**Issue by rengesser** [matlab2tikz/matlab2tikz#867]
I have some problems with exporting contour plots. 

- [x] Changing the LineWidth in contour plots is ignored by matlab2tikz:
```matlab
[X Y Z]=peaks;
subplot(1,2,1); contour(X,Y,Z,'LineWidth',1)
subplot(1,2,2); contour(X,Y,Z,'LineWidth',5)
matlab2tikz('contour_test.tex','standalone',true)
``` 
<img width="1127" alt="contour_linewidth_mwe" src="https://cloud.githubusercontent.com/assets/17144266/13286591/b2ba8386-db02-11e5-92db-e111f77a6314.png">
In matlab the two plots are having different line widths, but in matlab2tikz they don't. Adding the option "line width=5pt" to the addplot command in pgfplots would help.

- [x] A second problem for me is, that the color of a single contour line is ignored:
```matlab
[X Y Z]=peaks;
contour(X,Y,Z,[0 0],'r') % only one red colored contour line at level 0
matlab2tikz('contour_test2.tex','standalone',true)
``` 
<img width="1014" alt="contour_color_mwe" src="https://cloud.githubusercontent.com/assets/17144266/13286894/59b70aaa-db04-11e5-8d52-9ce64704db2d.png">
In matlab the line is red, in pgfplots it is black or blue.

**Comment by miscco** [comment]
We started doing some improvements to the options gathering , e.g. get*Info, which should help us catching those cases too. However i am not sure how fast we can tackle this.

**Comment by miscco** [comment]
Please try  #872, which should fix this issue.

**Comment by rengesser** [comment]
Works perfect for me, thanks a lot.

**Comment by miscco** [comment]
As the fix is merged i am closing this.
