### ISSUE TITLE
Export subplots to individual files

### ISSUE THREAD

**Issue by seebk** [matlab2tikz/matlab2tikz#869]
Is it possible to export every subplot in a figure into its own tex file? 

The issue is that I usually create subplots in a single matlab figure, but in a latex document I want to arrange the subplots using \subfloat. Hence, after exporting the figure with matlab2tikz I have to separate all axis and manually split the exported tex file into individual \tikzpictures wrapped by \subfloat.

Or is there any other more convenient way?

**Comment by miscco** [comment]
Why dot you just do figure(); instead of subfigure(nmk)? Then you run matlab2tikz for every individual figure.

**Comment by egeerardyn** [comment]
Unfortunately, there is no such feature in `matlab2tikz`.
However, using [subplot2plot](http://www.mathworks.com/matlabcentral/fileexchange/31136-subplot2plot), you should be able to convert the subplots to loose plots before passing them to matlab2tikz.

**Comment by egeerardyn** [comment]
Since `subplot2plot` can be used very easily to get the wanted result, I don't think we should incorporate such a feature into `matlab2tikz`. I will update our FAQ for this use-case such that other users can find this more easily.

**Comment by seebk** [comment]
Thanks, subplot2plot looks like it does what I need.
