### ISSUE TITLE
Blank lines in output file

### ISSUE THREAD

**Issue by nivek88** [matlab2tikz/matlab2tikz#877]
Hello,

is there any possibility to suppress empty lines in the output file while using m2t? Because with the standalone option set the generated PDF via LaTeX-compilation contains an uncropped figure. Deleting all the empty lines inside the tikz figure file affords the needed cropping. I especially have this issue because of using a caption inside the figure float of LaTeX.

Thanks.

**Comment by okomarov** [comment]
Hi nivek88, 
I am not sure what you mean. Can you please provide a small example of this behaviour with matlab code to reproduce the issue?

**Comment by egeerardyn** [comment]
I don't fully understand what you are trying to say.

In any case, you could also get rid of these empty lines by post-processing the files as they are generated by m2t:
 - read the file into MATLAB using `filescan`
 - replace empty lines, e.g. using `regexprep`
 - write out the file

Or if you are using Linux or Mac, you could also pass the file through something like `grep`, `awk` or `sed` to remove the empty lines.

If those empty lines really produce problems, I surely think we can adjust the code without a lot of problems. However, this will not be implemented immediately.

**Comment by nivek88** [comment]
`clc,
clear all,
close all,
%%
x=0:1;
y=0:1;
figure()
plot(x,y)
name='fig_01';
name_tikz=[name '.tex'];
matlab2tikz(name_tikz,'checkForUpdates',false,'standalone',true,'showInfo',false,...
    'noSize',false,'encoding','utf8','floatFormat','%.5f');
copyfile(name_tikz,'../LaTeX/Abbildungen')
movefile(name_tikz,'./Abbildungen')

name='fig_01_se';
Speichern(name)

function [] = Speichern(name)
name_tikz=[name '.tex'];
name_pdf=[name '.pdf'];
matlab2tikz(name_tikz,'checkForUpdates',false,'standalone',true,'showInfo',false,...
    'noSize',false,'encoding','utf8','floatFormat','%.5f');
copyfile(name_tikz,'../LaTeX/Abbildungen')
movefile(name_tikz,'./Abbildungen')
saveas(gcf,name_pdf,'pdf')
copyfile(name_pdf,'../LaTeX/Abbildungen')
movefile(name_pdf,'./Abbildungen')
end

`

This is the code i'm using. While Saving the figure using the m2t command directly after producing the figure LaTeX will handle the figure correctly and there is no white space between the caption and the graphic. This can't be reproduced using the Speichern function.

**Comment by okomarov** [comment]
Wihtespace between the figure and the caption? Are you sure it's a `matlab2tikz` problem? Can you please show the graphical output, because I cannot spot anything off by runing your code.

**Comment by egeerardyn** [comment]
@nivek88 How do you include the figure in your LaTeX document? 

Because, I rather think the problem is with the PDF figure you generate using the `Speichern` function, rather than `m2t`, since both of your calls to m2t are identical...

**Comment by nivek88** [comment]
It was
