### ISSUE TITLE
Contourf with meshgrid not working

### ISSUE THREAD

**Issue by mbrunnen** [matlab2tikz/matlab2tikz#881]
Hi!

Minimal (not) working example:
```matlab
[X, Y] = meshgrid(0:24,0:24);
Z = peaks(25);                                    % or any other 25x25 matrix
contourf(X,Y,Z);
matlab2tikz('foo.tex')
```
also not working, but shorter:
````matlab
[X, Y, Z] = peaks(25);
contourf(X,Y,Z);
matlab2tikz('foo.tex')
```
I get the error message:
```
Error using vertcat
Dimensions of matrices being concatenated are not consistent.

Error in matlab2tikz>drawFilledContours (line 2406)
    zerolevel = [0,          4;
```
Since the XData are matrices, because of meshgrid, the min/max of XData are vectors and not scalars. I think that causes the problem.

Best regards

**Comment by egeerardyn** [comment]
Hi, thank you for this complete bug report!
However, I cannot reproduce this using our latest develop branch on MATLAB 2014a and 2016a, so I presume it has been fixed already.

You might want to try out our development version: https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip

**Comment by mbrunnen** [comment]
Ok, at least it finishes without errors with the MWE. but if I use with my own pic i got this:
[heatpump_el.pdf](https://github.com/matlab2tikz/matlab2tikz/files/209915/heatpump_el.pdf)

**Comment by egeerardyn** [comment]
Hmm, that looks pretty bad. I think that behavior is already documented in  #723, but unfortunately, we haven't implemented the fix yet.
