### ISSUE TITLE
MATLAB error when exporting two-axes plot w/ multiple plots per axis

### ISSUE THREAD

**Issue by tcunis** [matlab2tikz/matlab2tikz#882]
Hello,

I have encountered a (rather seldom) MATLAB error when I tried to export a two-axes `plotyy` where there were multiple plots at a single axis, in combination with a legend.

A simple non-working example is given by ([test_plotyy2tikz.m](https://github.com/matlab2tikz/matlab2tikz/files/209941/test_plotyy2tikz.m.txt))

    x = 0:0.01:20;
    y1 = 200*exp(-0.05*x).*sin(x);
    y2 = 0.8*exp(-0.5*x).*sin(10*x);
    y3 = 0.8*exp(-0.5*x).*sin(x);

    figure
    %plots y2 and y3 both on secondary axis
    plotyy(x,y1,x,[y2; y3]);
    legend('y = e^{-0.05 x} \sin(x)', 'y = e^{-0.5 x} \sin(10 x)', 'y = e^{-0.5 x} \sin(x)');
    
    matlab2tikz('test_plotyy.tex');

This leads to the following MATLAB error: ([full stack trace](https://github.com/matlab2tikz/matlab2tikz/files/209942/plotyytikz_stacktrace.txt)  attached)

> Index exceeds matrix dimensions.
>
> Error in matlab2tikz>addPlotyyReference (line 754)
>            ref = m2t.axesContainers{end}.PlotyyReferences(ii);

Diving into matlab2tikz, the error seems to be raised because the lines 749--762 are executed twice, apparently because of the two plots on the secondary axis:

    749: elseif m2t.currentHandleHasLegend
    750:    % We are on the secondary axis
    [751--752]
    753:    for ii = 1:labelNum
    754:        ref = m2t.axesContainers{end}.PlotyyReferences(ii);
    [755--757]
    758:    end
    [759--761]
    762:    m2t.axesContainers{end}.PlotyyReferences = [];

But, for the assignment in line 762 the access of the `ii`-th element in line 750 fails the second time. My workaround now was to modify line 749 to

    749: elseif m2t.currentHandleHasLegend && ~isempty(m2t.axesContainers{end}.PlotyyReferences)

ensuring that the block is executed only once. Therewith, matlab2tikz runs successfully the tikz-outcome looks as expected.

**Comment by egeerardyn** [comment]
Thank you for reporting this bug and providing a patch even! 
I will look into it.

**Comment by egeerardyn** [comment]
Since #883, this produces good output.

I found that the legend text are not compilable, but that is known already in #647. 
Work-around is to either try out different options for `parseStrings`, `parseStringsAsMath` or to actually format those entries for the LaTeX interpreter (format the entries as `$...$` and make sure you do `set(legend(...), 'Interpreter','LaTeX')`).
