### ISSUE TITLE
Issue with fopen()

### ISSUE THREAD

**Issue by MarkoRamius** [matlab2tikz/matlab2tikz#887]
I have some issues with matlab2itkz_1.0.0 and octave 4.0.1.

When I try to save a plot, I get the following error message in octave:
```
error: Invalid call to fopen.  Correct usage is:

 -- Built-in Function: FID = fopen (NAME)
 -- Built-in Function: FID = fopen (NAME, MODE)
 -- Built-in Function: FID = fopen (NAME, MODE, ARCH)
 -- Built-in Function: [FID, MSG] = fopen (...)
 -- Built-in Function: FID_LIST = fopen ("all")
 -- Built-in Function: [FILE, MODE, ARCH] = fopen (FID)
error: called from
    print_usage at line 90 column 5
    matlab2tikz>fileOpenForWrite at line 412 column 14
    matlab2tikz>saveToFile at line 505 column 13
    matlab2tikz at line 352 column 1
    testSin at line 16 column 1
```

A quick and dirty fix for me was to modify the call to fopen() in matlab2tikz() as shown below.
This is not a recommended fix, since I assume that the third parameter is needed for some systems.
However, this way I can use matlab2tikz on my system with octave. I haven't yet had a chance to test it with matlab.

```
function fid = fileOpenForWrite(m2t, filename)
    encoding = switchMatOct({'native', m2t.cmdOpts.Results.encoding}, {});

    fid      = fopen(filename, 'w');%, encoding{:});
    if fid == -1
        error('matlab2tikz:fileOpenError', ...
            'Unable to open file ''%s'' for writing.', filename);
    end
end
```

**Comment by egeerardyn** [comment]
This should already be resolved in the `develop` branch. The solution is very similar to your work-around since in Octave there is less support for specifying arguments to `fopen`. Nevertheless, thank you for reporting this!

**Comment by MarkoRamius** [comment]
Well, I didn't check out the develop branch.

Thanks for the reply and keep up the good work.

At my university matlab is a widely used software, so matlab is the goto tool for most of my colleagues. For private use (thesis writing), I have no matlab available, so compatibility between matlab and octave saves my day, when tinkering with matlab scripts on my octave-using private computer.

**Comment by egeerardyn** [comment]
I have been lagging behind in releasing the develop branch (thesis writing and stuff).

With regard to MATLAB licensing: you might want to ask around at your department/university. Many universities tend to have a "total academic headcount" license such that each individual license is quite cheap to get.

In any case: I would also like to sincerely thank you for speaking up about your use case (MATLAB at work, Octave at home). That helps me to stay motivated to support Octave. 👍
