### ISSUE TITLE
deprecated environment warning and errors.

### ISSUE THREAD

**Issue by Merlethe** [matlab2tikz/matlab2tikz#888]
I have the three files 
matlab2tikz.m
m2tUpdater.m
m2tInputParser.m 
in my working folder, as I was instructed to do. I then have a plot open, and enter:
`matlab2tikz('myplot.tikz', 'height', '\figureheight', 'width', '\figurewidth');`

I get a 'deprecated environment' warning. I have matlab r2013a - the student version. The rest of the error is:

`Undefined function 'isAxis3D' for input arguments
of type 'double'.

Error in matlab2tikz>drawAxes (line 824)
    m2t.axesContainers{end}.is3D =
    isAxis3D(handle);

Error in matlab2tikz>saveToFile (line 450)
        m2t = drawAxes(m2t, relevantAxesHandle);

Error in matlab2tikz (line 352)
saveToFile(m2t, fid, fileWasOpen);`

Can you please help ?

**Comment by egeerardyn** [comment]
You need to place everything from our `src/` folder on your path. It is important that you also include the `private` folder as that is where some required functions are located.

The deprecation warning can be ignored most of the time. It's just there to warn you that we don't officially support versions older than R2014a anymore . Most of the time, everything runs just fine in an old version as we do try our best not to break things in old versions.
