### ISSUE TITLE
cleanfigure completely removes a line

### ISSUE THREAD

**Issue by AdamCooman** [matlab2tikz/matlab2tikz#912]
Hello!

In attachment, you can find a matlab figure I would like to export to tikz.
As usual, I call the cleanfigure function before calling matlab2tikz. But when I do this for this plot, one of the lines is completely removed. I think something is wrong somewhere :)

Kind greetings
ADAM

I am using the developement version on Matlab 2014a

**Comment by egeerardyn** [comment]
I can confirm this behavior (seen in real life), just waiting for the FIG file to upload decently.

**Comment by AdamCooman** [comment]
Apparently, I was using an old version of the code. The issue is fixed in the latest development version. Thanks for the very fast help! you fixed the issue before I could post it :)
