### ISSUE TITLE
missing title/legend in bode plot

### ISSUE THREAD

**Issue by Pratched** [matlab2tikz/matlab2tikz#913]
hello again ... I noticed some issues with m2t and `bode`. When bode-plotting a transfer function in matlab and using m2t for a .tikz-file, latex does not "print" the title of the bode-plot and there are only the colored lines of the graphs visible without the description of the legend.

I checked for this issue for couple of minutes, but didnt get any general results. So if this issue is already reported and there is a solution I apologize in advance ;)
``` 
A=tf(1, [55 8]);
B=tf([3 7], 1);

bode(A, B)
grid on
legend('A', 'B');
title('example')
``` 

edit: xlabel is also missing

**Comment by miscco** [comment]
So i cannot reproduce your error. There is the long standing issue with bode plots, that the "forget plot" option breaks tikz, so the original file doesnt compile. However,  if you remove all occurrences of "forget plot" then it compiles fine with title and all.

Please dont forget to check that you use the development version of m2t.

**Comment by egeerardyn** [comment]
@Pratched what version of MATLAB and matlab2tikz are you using?

**Comment by Pratched** [comment]
@miscco Hm alright, I actually developed this example to ensure, this is not a problem created only by my actual bode plot.
Regarding the development version: I thought the same, but changing to the original version didnt change anything.

@egeerardyn I actually downloaded tha latest one 2 weeks ago or so. I will download the version again right now and have a look. I am using Matlab R2016a (student use)

**Comment by miscco** [comment]
@Pratched Please make sure, that you download the develop branch not master

**Comment by Pratched** [comment]
so i should use develop branch and not master. Alright, thought the other way.

**Comment by miscco** [comment]
Yes develop it is. Master is the classic 1.0 version you can download from other places as well. develop is the shiny new version that gets polished.

**Comment by Pratched** [comment]
Mh. I did used the latest develop branch but no TexMaker says:
"! Missing } inserted.<inserted text>} \end{axis}" in Line 444 which would be somewhere in the tikz-file.
I try again and report...

**Comment by Pratched** [comment]
Second try does not change anything. I am recieving the error given above from latex and it does not creat a pdf at all.

The develop branch I use was updated 19 days ago...

**Comment by miscco** [comment]
Did you read my message stating that bode plots are currently corrupted and you need to remove the "forget plot" manually?

**Comment by Pratched** [comment]
yeah, but I could figure at what "forgot plot" means. clf? If so i restarted matlab many times

**Comment by PeterPablo** [comment]
take a look at the generated tex file.

**Comment by Pratched** [comment]
Oh okay, never had a look into the code of the tikz-file. Thank you!

**Comment by Pratched** [comment]
Legend and title works fine but fyi xlabel (frequency) does not appear. Works fine for me...could not figure out why but as I sad.

**Comment by miscco** [comment]
@Pratched I think you gonna have to learn to edit your files manually if you need Bodeplots. The problem is that MATLAB has a tremendously strange way of handling those plots that makes it really hard to treat them. 

For example the title and the xlabel for some reason appear in a separate axis, that is not visible. Why i cannot tell you but this is the reason you cannot see the xlabel (Frequency). The solution would be to add
```
xlabel={Frequency  (rad/s)},
```
Or whatever stands there at the bottom of your tikz file to the options of the second axis.

**Comment by Pratched** [comment]
yep you are right...but for now its okay.

I actually tried including this line...didnt work. The problem here is maybe, that each bode plot has 2 subplots (magnitude and phase of course) but Matlab is only setting xlabel for the second subplot (quite reasonable since both subplots got the same xlabel (frequency). If I have a look in the tex-code I can see, that `xlabel`... already is included below subplot 2. maybe LaTex got confues with subplots and a missing xlabel..I dont know. Thats a task for myself if there is some time and nothing else to do ;)

**Comment by egeerardyn** [comment]
@Pratched: right now, I would also advise against using `bode`. For just outputting, it's not really hard to implement the basic features of a bode plot by hand: `freqresp` and some ordinary `plot` commands (or `semilogx`) are your friends.

The problem is indeed that the `bode` function creates a pretty complicated internal structure which sometimes is not compatible with `matlab2tikz`. We will work on that, eventually.
