### ISSUE TITLE
addlegendentry syntax

### ISSUE THREAD

**Issue by urob** [matlab2tikz/matlab2tikz#921]
I noted that matlab2tikz puts a ";" after "\addlegendentry"-commands, which according to the documentation shouldn't be there (see the official manual or eg here: http://pgfplots.sourceforge.net/gallery.html)

i.e., matlab2tikz files would generate something like :
`\addplot [...] table[...]{...};
 \addlegendentry{blablab};
`

whereas it should be 
`\addplot [...] table[...]{...};
 \addlegendentry{blablab}
`

When compiling this results in an "Missing glyphs!" error, complaining about a "Missing character: There is no ; in font nullfont!"

(the compilation still seems to work fine and most editors tend to suppress the error. I just noticed when Lyx2.2 recently started complaining about it)

**Comment by egeerardyn** [comment]
Thank you for reporting this! You are absolutely right. 

I will tackle this at the same time as #801, since this is a very similar error on our side. You should see this in the upcoming release.

**Comment by urob** [comment]
Great, thanks -- and thanks for sharing and maintaining such a great script!!
