### ISSUE TITLE
TickLabelInterpreter isnt useable with m2t

### ISSUE THREAD

**Issue by Pratched** [matlab2tikz/matlab2tikz#926]
m2t is doing a great job so far...
But since I am using this tool a lot, I noticed something you might want to know.

Wenn setting 'YTickLabel' by using LaTeX code with 'TickLabelInterpreter', m2t seems to have trouble creating a tikz-file.

```
x= [1 2];
y= [1 2];

plot(x,y);
set(gca,'YLIM',[0 2],'Ytick',0:1:2,'YTickLabel',{'','$a$','$B_\mathrm{c}$'},'TickLabelInterpreter','latex');
matlab2tikz('example.tikz','showInfo',false);
```

This example should actually be enough to demonstrate the issue I am talking about. The error starts with something called `sprintf': 

>  Error using sprintf
> Function is not defined for 'cell' inputs.
> 
> Error in matlab2tikz>@(l)(sprintf('{%s}',l)) (line 5149)
>         tickLabels = cellfun(@(l)(sprintf('{%s}',l)), tickLabels, ...
> 
> Error in matlab2tikz>formatPgfTickLabels (line 5149)
>         tickLabels = cellfun(@(l)(sprintf('{%s}',l)), tickLabels, ...
> 
> Error in matlab2tikz>matlabTicks2pgfplotsTicks (line 5083)
>     pTickLabels = formatPgfTickLabels(m2t, isNeeded, tickLabels, ...
> 
> Error in matlab2tikz>getAxisTicks (line 1556)
>             matlabTicks2pgfplotsTicks(m2t, ticks, tickLabels, isAxisLog, tickLabelMode);
> 
> Error in matlab2tikz>getAxisOptions (line 1509)
>     [options] = getAxisTicks(m2t, handle, axis, options);
> 
> Error in matlab2tikz>drawAxes (line 888)
>     [m2t, yopts] = getAxisOptions(m2t, handle, 'y');
> 
> Error in matlab2tikz>saveToFile (line 481)
>         m2t = drawAxes(m2t, relevantAxesHandle);
> 
> Error in matlab2tikz (line 345)
>     m2t = saveToFile(m2t, fid, fileWasOpen);
> 
> Error in example (line 6)
> matlab2tikz('example.tikz','showInfo',false);

Thought you might be interessted, I will find I workaround probably somehow, but maybe this is easy to fix.

**Comment by PeterPablo** [comment]
did you give the develop branch a try? if not, please do so and report
back.

**Comment by Pratched** [comment]
Yes, I updated the develope branch this weekend. :/

**Comment by miscco** [comment]
I havent really looked into it, but i would suggest to just omit 'TickLabelInterpreter'.

For me it doesnt really have any benefit.

**Comment by Pratched** [comment]
Well I cant use latex code in matlab such as $a_\mathrm{b}$ that's actually the reason.

**Comment by miscco** [comment]
did you try to enter it as a simple array?
```matlab
['','$a$','$B_\mathrm{c}$']
```

**Comment by Pratched** [comment]
Do you mean like this?
```
set(gca,'YLIM',[0 2],'Ytick',0:1:2,'YTickLabel',['','$a$','$B_\mathrm{c}$']);
```
The following figure is plotted.
<img width="399" alt="capture" src="https://cloud.githubusercontent.com/assets/19487828/16631789/3b5a198c-43c1-11e6-8447-9690a5f9d76f.PNG">

I actually always used { instead of [ for `YTickLabel`

**Comment by Pratched** [comment]
and for { I
<img width="410" alt="capture" src="https://cloud.githubusercontent.com/assets/19487828/16632206/5ace24b4-43c3-11e6-8a99-246182ab4d49.PNG">
 recieve

**Comment by miscco** [comment]
No i meant 
```
set(gca,'YLIM',[0 2],'Ytick',0:1:2,'YTickLabel',['','$a$','$B_\mathrm{c}$'], 'TickLabelInterpreter', 'Latex');
```

**Comment by Pratched** [comment]
If I run the script like you suggest (with [), I do recieve the same m2t error and there are no ticks in the figure. With { I do get the m2t error, but there are latex interpreted ticks...

**Comment by miscco** [comment]
Arg sorry, my bad. Multitasking is not optimal.

As a short workaround change the ofending line to:
```matlab
tickLabels = cellfun(@(l)(sprintf('{%s}',l{:})), tickLabels,...
```

I will try to find a more permanent solution that works with other stuff too

**Comment by Pratched** [comment]
Okay, thanks a lot, but I am not quite sure WHERE to change this line.

**Comment by miscco** [comment]
In the error message of MATLAB you can just click on the upper most line (line 5149).
```
Error in matlab2tikz>@(l)(sprintf('{%s}',l)) (line 5149)
tickLabels = cellfun(@(l)(sprintf('{%s}',l)), tickLabels, ...
```

**Comment by Pratched** [comment]
Alright, thanks a lot for the quick response!

**Comment by miscco** [comment]
I just submitted a pull request that should fix this issue for good.
