### ISSUE TITLE
Bar plots not compiling

### ISSUE THREAD

**Issue by acmelhorn** [matlab2tikz/matlab2tikz#930]
My normal plots seem to work fine but I have not been able to compile anything when using bar plots.  Any help would be appreciated.  Thank you!

Matlab code:
```
y2 = [
     31.38141 31.27551
     33.63841 33.76723
     35.66314 36.06678
     ];

barPlot2 = barh(y2);
box off;

barPlot2(2).FaceColor = [173,216,230]./255;
barPlot2(1).FaceColor = [0 0 1.0];

ax = gca;
ax.YTickLabel = {'label 3' 'label 2 'label 1'};
xlabel('production (GWh)')

xlim([30 37])

c = {'set 2','set 1'};
order=[2 1];
legend(barPlot2(order),c{order},'Location','southeast');
legend boxoff;

matlab2tikz('test1.tex', 'height', '\fheight', 'width', '\fwidth')
````

latex code:
```
\documentclass{article}

  \usepackage{pgfplots}
  \pgfplotsset{compat=newest}
  %% the following commands are sometimes needed
  \usetikzlibrary{plotmarks}
  \usepackage{grffile}
  \usepackage{amsmath}
  %% you may also want the following commands
  %\pgfplotsset{plot coordinates/math parser=false}
  %\newlength\figureheight
  %\newlength\figurewidth

\begin{document}
	TikZ: \expandafter\csname ver@tikz.sty\endcsname \\
	pgfplots: \expandafter\csname ver@pgfplots.sty\endcsname \\

	\centering
    \newlength\fheight 
    \newlength\fwidth 
    \setlength\fheight{\linewidth} 
    \setlength\fwidth{\linewidth}
	\input{test1.tex}
\end{document}
```

Error list is way to long to list.

software versions:
TikZ: 2013/12/13 v3.0.0 (rcs-revision 1.142)
pgfplots: 2015/05/02 v1.12.1 Data Visualization (1.12.1)

Thank you again!

**Comment by okomarov** [comment]
@acmelhorn Can you make sure you are using the most recent version from the development branch?

I cannot reproduce your problem.

**Comment by egeerardyn** [comment]
I cannot reproduce this either in R2014b both on `master` and `develop`. I don't get any errors, except in your MATLAB code that `ax.YTickLabel = {'label 3' 'label 2 'label 1'};` is not valid (it is missing a quotation mark).

Unless you can provide more detailed information about the error (if it is too long, you can upload it to pastebin or gist).

**Comment by acmelhorn** [comment]
Thank you for your comments!  I believe I found the answer.  In one of my labels which I changed before I upload the code I had an "%" and I did not include an escape character.  Works fine for plots in matlab but not latex.  I didn't realize I had not tested the code I uploaded here either.  Thank you again and I apologize if I wasted anyone's time.
