### ISSUE TITLE
findobj error

### ISSUE THREAD

**Issue by phwi** [matlab2tikz/matlab2tikz#940]
I just commented to an already closed Issue (findobj error in drawAnnotations #892), which is properly not wanted. That's why I am raising this issue here again:

I am still receiving the following error (R2015b and R2016a) and I've tested the devolopment branch as well as the main branch, but always with the same result:

```
Error using findobj
Invalid parameter/value pair arguments.

Error in matlab2tikz>drawAnnotations (line 2515)
        annotHandles = findobj(get(annotPanes,'Children'),'Visible','on');

Error in matlab2tikz>saveToFile (line 459)
    m2t = drawAnnotations(m2t);

Error in matlab2tikz (line 352)
saveToFile(m2t, fid, fileWasOpen);
```

You will be able to reproduce the error in the following way:

```
figure
plot(rand(10),rand(10)
```

now edit the plot manually: tools --> edit plot --> click on axes --> more properties --> linewidth change to 5 pt --> undock plot --> uncheck edit plot --> close "figures" environment (which is in the background) --> try to use matlab2tikz on the remaining figure/plot... and there is the error.

If you are doing the exact same thing by using

`set(gca,'LineWidth',5)`

instead of manually changing it with the edit plot function and then trying to use matlab2tikz everything works just fine. So the problem seems to occur when doing manual plot editing.

I am new to matlab2tikz and maybe manual plot editing has to be avoided or is not supported in some way? I am sorry in this case... 
But if it should be possible to manual edit a plot and then export it with matlab2tikz, there you have a possibility to check how the problem occurs.

**Comment by okomarov** [comment]
Please make sure you are using the development branch. The error shows [line numbers and code](https://github.com/matlab2tikz/matlab2tikz/blob/master/src/matlab2tikz.m#L2515) which is from the master branch.

**Comment by egeerardyn** [comment]
Thank you for the detailed bug report!

Normally, it should not be an issue to edit the figure manually like you describe: behind the scenes, manual editing (actually, you can get similar results with `inspect(gca)` without all that clicking around) should do exactly the same as using `set(...)`).

In the develop branch, I cannot reproduce the error you are reporting (even using all the clicking and so on). In `master` (as indicated in #892), the error is present.

As @okomarov said, please do make sure that you are actually using the `develop` branch. You can check which `matlab2tikz.m` file you are using by typing `which matlab2tikz`. Please double check that this file is actually the one you have downloaded from https://github.com/matlab2tikz/matlab2tikz/archive/develop.zip

If that still does not change anything, please create a FIG file of the figure (in your figure window: File >Save) that does not convert well such that we at least can try to reproduce it on our end.

**Comment by phwi** [comment]
Thank you for the fast feedback.

The fault was on my side... I downloaded the develop branch yesterday, unzipped it and replaced all files from my matlab2tikz folder. Actually it was the exact same link as the downloaded file was named matlab2tikz-develop (1).zip, when I tried to download it again today (and the old zip was obviously still in the downloads folder).

Nevertheless after unzipping and replacing today, it solved my problem. I actually don't how I could have been failing yesterday in replacing the files the correct way, must have been some stupid copy/paste (master branch still in the clipboard) mistake - maybe I was too tired yesterday.

When I replaced all files with the ones from the develop branch again today, it solved the problem. I am very sorry for the inconvenience!

I think you can close this issue, as it must have been my own incapability of copying and pasting :-)

**Comment by egeerardyn** [comment]
@phwi Don't worry about it 😄 happens to us all at one time or another.
