### ISSUE TITLE
Use text=colorname instead of font=\color{colorname}

### ISSUE THREAD

**Issue by TorbjornT** [matlab2tikz/matlab2tikz#946]
This came up in http://tex.stackexchange.com/questions/329315/pgfplotsset-append-style-is-not-appended-to-tikzpicture-axis-environment

If you for example do

    x = [1,100];
    plot(x)
    set(gca,'xcolor','black')
    matlab2tikz('demo.tex')

then `demo.tex` will contain the line

    every x tick label/.append style={font=\color{black}}

I'd suggest, based on the comments on TeX.SX, to use

    every x tick label/.append style={text=black}

instead. That leaves the `font` key open for external modifications. The same goes for any other situation where you set the color of text, use the `text` key instead of `font=\color`.

**Comment by phwi** [comment]
I just provided the solution here:
https://github.com/matlab2tikz/matlab2tikz/issues/947

Is unfortunately the same issue :-). TorbjornT was faster.

**Comment by TorbjornT** [comment]
See #947 as @phwi mentioned.

**Comment by egeerardyn** [comment]
Thank you for the bug report nevertheless. As this is closed, we will track everything further in #947
