### ISSUE TITLE
Legend mistake when using plot(x,y,'linestyle','none')

### ISSUE THREAD

**Issue by pfbuxton** [matlab2tikz/matlab2tikz#954]
When plotting using `'linestyle','none'` matlab2tikz leaves the line on when doing a legend.

Here is a simple example, with sample output.

There are two workarounds:

-  `scatter(x,y)`

-  `plot(x,y,'color','white')` (although this is likely to add white lines to other plots).

``` matlab
clear;

figure; hold on;
x = [1 2 3];
y = [1.2 2.1 2.8];
P(1) = plot( x, y, 'MarkerFaceColor','Blue', 'MarkerEdgeColor','Blue', 'Marker','o', 'MarkerSize',6.0, 'LineStyle','none', 'DisplayName','Scattered data' );
pfit = polyfit(x,y,1);
y_fit = polyval(pfit,x);
P(2) = plot( x, y_fit, 'Color','Blue', 'DisplayName','$y=mx+c$ fit' );

legend1 = legend( P, 'Location','NorthWest' );
set( legend1, 'Interpreter','latex' );

matlab2tikz( 'test.tikz', 'standalone',true );
system( 'pdflatex test.tikz' );
```

![image](https://cloud.githubusercontent.com/assets/4923588/20095519/b685147a-a59d-11e6-8f18-5153a00b6efb.png)

**Comment by egeerardyn** [comment]
Should be fixed by #968. Please feel free to re-open, if you are still getting this problem in the `develop` branch.
