### ISSUE TITLE
How to avoid effect of Matlab figure size (in display)

### ISSUE THREAD

**Issue by abhinavgaur** [matlab2tikz/matlab2tikz#975]
I notice that the tex figure generated using **matlab2tikz** is depending on the size of figure that is visible in display. Because of this, I have to play a lot with scaling in the Latex document which I wish to avoid. 

Example, for my publication, I want that the tikz figure (in scale 1) should be a figure of size 2.5 inches by 2.5 inches (including axis, labels, everything) on an A4 sheet. Despite giving following options during the creation of the matlab fig file, i.e.,
```

    f.PaperPositionMode = 'manual';
    f.PaperType = 'A4';
    f.PaperPosition = [0,0,figWidth,figHeight];
    f.Renderer = 'painters';
```
, the scale=1 size of final figure tex file produced, when compiled depends on some other unknown parameters. Because, two images, which look different size in display, but compiled using above options gave different sized figures. I also played around with the `figure.OuterPosition, figure.InnerPosition, axis.OuterPosition`, and `axis.Position properties,` but to no avail. 

Are there any options (that I may be not aware of) in matlab2tikz, using which I can specify the ideal size (on paper of specific size) for the figure ?  Or am I missing something ?

**Comment by egeerardyn** [comment]
Normally, the `Position` field of your MATLAB figure is used to determine the size of the eventual output in TikZ. Next to that, there are the arguments `width` and `height` for matlab2tikz which allow you to adjust the output size to your liking (as indicated in the documentation). There is currently one caveat when specifying the size in the last manner: there are some rudimentary checks that try to preserve the aspect ratio of your figure which have precedence over the options you specify (this is something we have been meaning to get rid off (see #622 for more info and an in-code workaround)).

Personally, I would recommend (as indicated in the README), to supply width and height using some LaTeX sizes (e.g. `\figurewidth`/`\figureheight` which you have to define yourself). That allows you to change the size of your figures dynamically during compilation. The only downside is that not all elements size by exactly the same factor; but for most things it does something more or less reasonable.

**Comment by abhinavgaur** [comment]
In my figure, I am not defining the Position attribute of figure, so its values are dependent on the displayed image size.  I do however call my matlab2tikz command with the 'width' option and set it using \setlength in my Latex document. I dont set figure height because it is square axis figure. 

So, if I have to draw two comparative figures (say figures 1a and 1b) without having to set different scales for them in the Latex document, I should be setting their Figure position properties to be same to be able to achieve that ?
