### ISSUE TITLE
\definecolor -> \providecolor?

### ISSUE THREAD

**Issue by jgmakin** [matlab2tikz/matlab2tikz#979]
matlab2tikz has the nice feature of allowing the user to pass strings and RGB values for 'extraColors', and then defining them at the top of the .tex file.  What would be even nicer would be to be able to override the definition from outside the .tex file.  For example, a common use case (for me at least) is to, at some point long after my figure files (.texs) have been written by matlab2tikz, change the global definition of one of the colors ("ok, now let's have the latent variables be greenish-blue instead of redish-brown...").  I'd prefer not to have to edit every single figure file, but just change one line in the master file that calls them.

The "fix" to matlab2tikz is easy: just replace \definecolor with \providecolor.  Both are from the "xcolor" package, although I suppose the latter is not in the "color" package.  I've made this change to my local version of matlab2tikz, but I think it would be useful for others.

**Comment by egeerardyn** [comment]
Thank you for your kind words and suggestions.
We have in the past been thinking about similar features to allow for customization, but if it's really that simple, to help you out for your use case, I am completely on board.

Of course, you are always welcome to file a pull request with this change. For first-time contributions, we normally take care of a lot of the minutiae of making sure the tests pass.

**Comment by jgmakin** [comment]
Thanks.  I've filed the pull request.
