### ISSUE TITLE
plotting in grayscale, line textures

### ISSUE THREAD

**Issue by jruizaranguren** [matlab2tikz/matlab2tikz#982]
I am creating a simple line plot with a couple of lines. 
Something like plot(1:100,x,1:100,y,1:100,z);

I'm struggling to get a gray-scale plot. Is there any easy way to indicate that I wish to have a gray scale color scheme for lines through matlab2tikz?

Would it be possible to automatically select different line textures? 

Thanks.

**Comment by okomarov** [comment]
This is a level of customization that matlab2tikz does not have. You should plot in grayscale in Matlab, and then matlab2tikz will do its magic.
