### ISSUE TITLE
Legend using plot(x,y,'.')

### ISSUE THREAD

**Issue by PhysikerErlangen** [matlab2tikz/matlab2tikz#989]
Hello,
I've been plotting some data points like this:
```matlab
plot(x1,y1, '.',' DisplayName','Used data points');
plot(x2,y2, 'DisplayName','Used data points'):
legend('show');
matlab2tikz('test.tex');
```

In my Latex document the legend was displayed as follows:
![image](https://cloud.githubusercontent.com/assets/13521689/25223947/d2fa8daa-25b4-11e7-858c-61ba8d016c84.png)

In order to have it correctly, I needed to change the following codes in the .tex code:
```latex
\addplot [color=black, draw=none, mark size=1.7pt, mark=*, mark options={solid, black}]
```
to
```latex
\addplot [color=black, only marks, mark size=1.7pt, mark=*, mark options={solid, black}]
```
The final result looks like this:

![image](https://cloud.githubusercontent.com/assets/13521689/25223890/a6ef617c-25b4-11e7-8ec0-1a8fa8fd9cd3.png)

Best,
Florian

**Comment by egeerardyn** [comment]
Thank you for bringing this to our attention. At first sight, I would say this is certainly something we can change in how we translate the figure.

**Comment by egeerardyn** [comment]
Hmm, apparently we already had a bug report for this: #954, and even a fix in the `[develop](https://github.com/matlab2tikz/matlab2tikz/tree/develop)` branch since #968. If you can still reproduce this in `develop`, feel free to re-open this issue.
